-- 2026-09-10-p3d6-15-more-tables.sql (auto-generated by scripts/sql/p3d6_15_more_tables_gen.py)
-- P3-D.6 阶段 1 基础 任务 1.6 14 张新表 SQL DDL 落档 (per 守门 #13 W/T/M 100% 覆盖 + 0 混在)
-- (per brief docs/briefs/p3-d6-1-6-15-more-tables.md §1.1 14 张新表 + 守门 #9 v20 子代理 dispatch 必先 brief 落档)
--
-- 守门 #13 a 100% RLS: ENABLE + FORCE + 6 类 policy (per v0.92 rls_7_policy_gen.py, 跳过 health_visibility 因表无 health_status 列)
-- 守门 #13 b 物理删除禁止: 4 类 CRUD delete 仅 platform_admin
-- 守门 #13 c M SCD Type 2: pgpool_version 字段 (6 张 M 表)
-- 守门 #13 d T 100% audit: WORM append-only trigger BEFORE UPDATE OR DELETE RAISE EXCEPTION (5 张 T 表, per ADR-0043)
-- 守门 #19 v19 复用 v0.92 rls_7_policy_gen.py 6 类 RLS policy 模式 + v0.97 DROP IF EXISTS 兼容 PG 9.5+ idempotent
-- 守门 #1 禁回溯叙事: 不重写 V0.1 15 张 DDL, 仅新 commit + 14 张新表 DDL
-- 守门 #11 缺标比错标: P3-D.6 阶段 1 基础阶段 14 张新表 schema, P2 阶段 worker 子代理 ALTER TABLE 改字段
-- 守门 #14 v4 Mavis 审核 author=Ulysses
--
-- 14 张新表 W/T/M 分类 (per 守门 #13 横展规则, 100% 覆盖, 0 混在):
--   - M (Master) 6 张: agent_trust_score_history + canvas_permissions + gamify_achievements +
--                    gamify_rewards + gamify_leaderboards + gamify_avatar_customization
--     物理删除禁止 + SCD Type 2 (pgpool_version) + 100% RLS
--   - T (Transaction) 5 张: agent_session_audit + gamify_xp_history +
--                    gamify_vote_audit + gamify_sticky_note_audit + gamify_confetti_audit
--     物理删除禁止 + 100% audit WORM trigger (per ADR-0043) + 100% RLS
--   - W (Work) 3 张: canvas_presence_cursors (5 min) + canvas_followers (5 min) +
--                    gamify_level_progress (30 days)
--     物理删除 + 短 TTL retention_period + 100% RLS

BEGIN;

BEGIN;
-- ==========================================
-- 1. agent_trust_score_history 表 (per V0.2 TrustScoreTier 5 变体 + ARG.G-4 + 守门 #13 c SCD Type 2 (pgpool_version 字段))
-- W/T/M 分类: M
-- 说明: Trust score 变化历史 (per V0.2 强类型 enum TrustScoreTier 5 档)
-- ==========================================
CREATE TABLE IF NOT EXISTS agent_trust_score_history (
    -- 业务字段 (per V0.2 TrustScoreTier 5 变体 + ARG.G-4)
    id                 UUID NOT NULL PRIMARY KEY,
    tenant_id          UUID NOT NULL,
    agent_id           UUID NOT NULL,
    score              REAL NOT NULL CHECK (score >= 0.0 AND score <= 1.0),
    tier               TEXT NOT NULL CHECK (tier IN ('Untrusted', 'Low', 'Medium', 'High', 'VeryHigh')),
    from_state         TEXT,
    to_state           TEXT NOT NULL,
    change_reason      TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by         UUID NOT NULL,
    pgpool_version     BIGINT NOT NULL DEFAULT 1,
    schema_name        TEXT NOT NULL DEFAULT 'public',
    -- 显式主键
    PRIMARY KEY (id)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_agent_trust_score_history_agent_id
    ON agent_trust_score_history (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_trust_score_history_tier
    ON agent_trust_score_history (tier);
CREATE INDEX IF NOT EXISTS idx_agent_trust_score_history_created_at
    ON agent_trust_score_history (created_at);
-- 当前 SCD Type 2 "有效" version 视图 (per V0.82 pgpool_version 模式)
CREATE OR REPLACE VIEW v_agent_trust_score_history_current AS
SELECT DISTINCT ON (tenant_id, id) *
FROM agent_trust_score_history
ORDER BY tenant_id, id, pgpool_version DESC;


-- ==========================================
-- 1.RLS  RLS 6 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 7 类中跳过 health_visibility (表无 health_status 列, per v0.93 缺口 (d) 修)
-- ==========================================
ALTER TABLE agent_trust_score_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_trust_score_history FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- agent_trust_score_history 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS agent_trust_score_history_select ON agent_trust_score_history;
CREATE POLICY agent_trust_score_history_select ON agent_trust_score_history
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_trust_score_history_insert ON agent_trust_score_history;
CREATE POLICY agent_trust_score_history_insert ON agent_trust_score_history
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_trust_score_history_update ON agent_trust_score_history;
CREATE POLICY agent_trust_score_history_update ON agent_trust_score_history
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_trust_score_history_delete ON agent_trust_score_history;
CREATE POLICY agent_trust_score_history_delete ON agent_trust_score_history
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    ); -- 守门 #13 b 物理删除禁止: 仅 platform_admin

-- agent_trust_score_history schema_isolation policy (per v0.91 §8.3 映射表 5, 14 张新表都含 schema_name 列)
DROP POLICY IF EXISTS agent_trust_score_history_schema_isolation ON agent_trust_score_history;
CREATE POLICY agent_trust_score_history_schema_isolation ON agent_trust_score_history
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

-- agent_trust_score_history platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
DROP POLICY IF EXISTS agent_trust_score_history_platform_admin ON agent_trust_score_history;
CREATE POLICY agent_trust_score_history_platform_admin ON agent_trust_score_history
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;

BEGIN;
-- ==========================================
-- 2. agent_session_audit 表 (per A3.2 + ADR-0043 WORM append-only + 守门 #13 d T 100% audit WORM append-only (per ADR-0043))
-- W/T/M 分类: T
-- 说明: Session audit WORM append-only (per A3.2 状态变化 audit + V0.3 业务方法)
-- ==========================================
CREATE TABLE IF NOT EXISTS agent_session_audit (
    -- 业务字段 (per A3.2 + ADR-0043 WORM append-only)
    id                 UUID NOT NULL PRIMARY KEY,
    tenant_id          UUID NOT NULL,
    agent_id           UUID NOT NULL,
    session_id         UUID NOT NULL,
    action             TEXT NOT NULL CHECK (action IN ('create', 'update', 'delete', 'expire', 'revoke', 'refresh')),
    from_state         TEXT,
    to_state           TEXT,
    at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version            BIGINT NOT NULL DEFAULT 1,
    metadata           JSONB DEFAULT '{}'::jsonb,
    schema_name        TEXT NOT NULL DEFAULT 'public',
    -- 显式主键
    PRIMARY KEY (id)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_agent_session_audit_agent_id
    ON agent_session_audit (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_session_audit_session_id
    ON agent_session_audit (session_id);
CREATE INDEX IF NOT EXISTS idx_agent_session_audit_at
    ON agent_session_audit (at);
CREATE INDEX IF NOT EXISTS idx_agent_session_audit_action
    ON agent_session_audit (action);

-- ==========================================
-- 2.RLS  RLS 6 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 7 类中跳过 health_visibility (表无 health_status 列, per v0.93 缺口 (d) 修)
-- ==========================================
ALTER TABLE agent_session_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_session_audit FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- agent_session_audit 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS agent_session_audit_select ON agent_session_audit;
CREATE POLICY agent_session_audit_select ON agent_session_audit
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_session_audit_insert ON agent_session_audit;
CREATE POLICY agent_session_audit_insert ON agent_session_audit
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_session_audit_update ON agent_session_audit;
CREATE POLICY agent_session_audit_update ON agent_session_audit
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_session_audit_delete ON agent_session_audit;
CREATE POLICY agent_session_audit_delete ON agent_session_audit
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    ); -- 守门 #13 b 物理删除禁止: 仅 platform_admin

-- agent_session_audit schema_isolation policy (per v0.91 §8.3 映射表 5, 14 张新表都含 schema_name 列)
DROP POLICY IF EXISTS agent_session_audit_schema_isolation ON agent_session_audit;
CREATE POLICY agent_session_audit_schema_isolation ON agent_session_audit
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

-- agent_session_audit platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
DROP POLICY IF EXISTS agent_session_audit_platform_admin ON agent_session_audit;
CREATE POLICY agent_session_audit_platform_admin ON agent_session_audit
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

-- ==========================================
-- 2.WORM  WORM append-only audit trigger (per 守门 #13 d + ADR-0043)
-- 仅允许 INSERT, UPDATE/DELETE 触发异常
-- ==========================================
CREATE OR REPLACE FUNCTION agent_session_worm_trigger() RETURNS TRIGGER AS $$
BEGIN
    -- WORM append-only: 仅 INSERT 允许, UPDATE/DELETE 触发异常
    IF (TG_OP = 'UPDATE' OR TG_OP = 'DELETE') THEN
        RAISE EXCEPTION 'agent_session_audit is WORM append-only (per 守门 #13 d + ADR-0043)';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_agent_session_audit_worm ON agent_session_audit;
CREATE TRIGGER trg_agent_session_audit_worm
    BEFORE UPDATE OR DELETE ON agent_session_audit
    FOR EACH ROW
    EXECUTE FUNCTION agent_session_worm_trigger();

COMMIT;

BEGIN;
-- ==========================================
-- 3. canvas_permissions 表 (per A12.7 PermissionLevel 3 变体 + 守门 #13 c SCD Type 2 (pgpool_version 字段))
-- W/T/M 分类: M
-- 说明: Canvas 3 档权限 view/comment/edit (per A12.7)
-- ==========================================
CREATE TABLE IF NOT EXISTS canvas_permissions (
    -- 业务字段 (per A12.7 PermissionLevel 3 变体)
    id                 UUID NOT NULL PRIMARY KEY,
    tenant_id          UUID NOT NULL,
    canvas_id          UUID NOT NULL,
    user_id            UUID NOT NULL,
    permission_level   TEXT NOT NULL CHECK (permission_level IN ('View', 'Comment', 'Edit')),
    granted_by         UUID NOT NULL,
    granted_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at         TIMESTAMPTZ,
    pgpool_version     BIGINT NOT NULL DEFAULT 1,
    schema_name        TEXT NOT NULL DEFAULT 'public',
    -- 显式主键
    PRIMARY KEY (id)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_canvas_permissions_canvas_id
    ON canvas_permissions (canvas_id);
CREATE INDEX IF NOT EXISTS idx_canvas_permissions_user_id
    ON canvas_permissions (user_id);
CREATE INDEX IF NOT EXISTS idx_canvas_permissions_permission_level
    ON canvas_permissions (permission_level);
-- 当前 SCD Type 2 "有效" version 视图 (per V0.82 pgpool_version 模式)
CREATE OR REPLACE VIEW v_canvas_permissions_current AS
SELECT DISTINCT ON (tenant_id, id) *
FROM canvas_permissions
ORDER BY tenant_id, id, pgpool_version DESC;


-- ==========================================
-- 3.RLS  RLS 6 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 7 类中跳过 health_visibility (表无 health_status 列, per v0.93 缺口 (d) 修)
-- ==========================================
ALTER TABLE canvas_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE canvas_permissions FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- canvas_permissions 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS canvas_permissions_select ON canvas_permissions;
CREATE POLICY canvas_permissions_select ON canvas_permissions
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS canvas_permissions_insert ON canvas_permissions;
CREATE POLICY canvas_permissions_insert ON canvas_permissions
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS canvas_permissions_update ON canvas_permissions;
CREATE POLICY canvas_permissions_update ON canvas_permissions
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS canvas_permissions_delete ON canvas_permissions;
CREATE POLICY canvas_permissions_delete ON canvas_permissions
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    ); -- 守门 #13 b 物理删除禁止: 仅 platform_admin

-- canvas_permissions schema_isolation policy (per v0.91 §8.3 映射表 5, 14 张新表都含 schema_name 列)
DROP POLICY IF EXISTS canvas_permissions_schema_isolation ON canvas_permissions;
CREATE POLICY canvas_permissions_schema_isolation ON canvas_permissions
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

-- canvas_permissions platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
DROP POLICY IF EXISTS canvas_permissions_platform_admin ON canvas_permissions;
CREATE POLICY canvas_permissions_platform_admin ON canvas_permissions
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;

BEGIN;
-- ==========================================
-- 4. canvas_presence_cursors 表 (per A12.2 presence cursor + 守门 #13 a 物理删除 + 短 TTL retention_period = 5 minutes)
-- W/T/M 分类: W
-- 说明: Presence cursor 推送 (per A12.2, retention 5 min)
-- ==========================================
CREATE TABLE IF NOT EXISTS canvas_presence_cursors (
    -- 业务字段 (per A12.2 presence cursor)
    id                 UUID NOT NULL PRIMARY KEY,
    tenant_id          UUID NOT NULL,
    canvas_id          UUID NOT NULL,
    user_id            UUID NOT NULL,
    x                  REAL NOT NULL,
    y                  REAL NOT NULL,
    color              TEXT NOT NULL DEFAULT '#FF0000',
    last_active        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    schema_name        TEXT NOT NULL DEFAULT 'public',
    -- 显式主键
    PRIMARY KEY (id)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_canvas_presence_cursors_canvas_id
    ON canvas_presence_cursors (canvas_id);
CREATE INDEX IF NOT EXISTS idx_canvas_presence_cursors_user_id
    ON canvas_presence_cursors (user_id);
CREATE INDEX IF NOT EXISTS idx_canvas_presence_cursors_last_active
    ON canvas_presence_cursors (last_active);

-- ==========================================
-- 4.RLS  RLS 6 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 7 类中跳过 health_visibility (表无 health_status 列, per v0.93 缺口 (d) 修)
-- ==========================================
ALTER TABLE canvas_presence_cursors ENABLE ROW LEVEL SECURITY;
ALTER TABLE canvas_presence_cursors FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- canvas_presence_cursors 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS canvas_presence_cursors_select ON canvas_presence_cursors;
CREATE POLICY canvas_presence_cursors_select ON canvas_presence_cursors
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS canvas_presence_cursors_insert ON canvas_presence_cursors;
CREATE POLICY canvas_presence_cursors_insert ON canvas_presence_cursors
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS canvas_presence_cursors_update ON canvas_presence_cursors;
CREATE POLICY canvas_presence_cursors_update ON canvas_presence_cursors
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS canvas_presence_cursors_delete ON canvas_presence_cursors;
CREATE POLICY canvas_presence_cursors_delete ON canvas_presence_cursors
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    ); -- 守门 #13 b 物理删除禁止: 仅 platform_admin

-- canvas_presence_cursors schema_isolation policy (per v0.91 §8.3 映射表 5, 14 张新表都含 schema_name 列)
DROP POLICY IF EXISTS canvas_presence_cursors_schema_isolation ON canvas_presence_cursors;
CREATE POLICY canvas_presence_cursors_schema_isolation ON canvas_presence_cursors
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

-- canvas_presence_cursors platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
DROP POLICY IF EXISTS canvas_presence_cursors_platform_admin ON canvas_presence_cursors;
CREATE POLICY canvas_presence_cursors_platform_admin ON canvas_presence_cursors
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;

BEGIN;
-- ==========================================
-- 5. canvas_followers 表 (per A12.4 follow mode + 守门 #13 a 物理删除 + 短 TTL retention_period = 5 minutes)
-- W/T/M 分类: W
-- 说明: Follow mode (per A12.4, retention 5 min)
-- ==========================================
CREATE TABLE IF NOT EXISTS canvas_followers (
    -- 业务字段 (per A12.4 follow mode)
    id                 UUID NOT NULL PRIMARY KEY,
    tenant_id          UUID NOT NULL,
    canvas_id          UUID NOT NULL,
    follower_id        UUID NOT NULL,
    followee_id        UUID NOT NULL,
    started_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_active        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    schema_name        TEXT NOT NULL DEFAULT 'public',
    -- 显式主键
    PRIMARY KEY (id)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_canvas_followers_canvas_id
    ON canvas_followers (canvas_id);
CREATE INDEX IF NOT EXISTS idx_canvas_followers_follower_id
    ON canvas_followers (follower_id);
CREATE INDEX IF NOT EXISTS idx_canvas_followers_followee_id
    ON canvas_followers (followee_id);
CREATE INDEX IF NOT EXISTS idx_canvas_followers_last_active
    ON canvas_followers (last_active);

-- ==========================================
-- 5.RLS  RLS 6 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 7 类中跳过 health_visibility (表无 health_status 列, per v0.93 缺口 (d) 修)
-- ==========================================
ALTER TABLE canvas_followers ENABLE ROW LEVEL SECURITY;
ALTER TABLE canvas_followers FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- canvas_followers 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS canvas_followers_select ON canvas_followers;
CREATE POLICY canvas_followers_select ON canvas_followers
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS canvas_followers_insert ON canvas_followers;
CREATE POLICY canvas_followers_insert ON canvas_followers
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS canvas_followers_update ON canvas_followers;
CREATE POLICY canvas_followers_update ON canvas_followers
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS canvas_followers_delete ON canvas_followers;
CREATE POLICY canvas_followers_delete ON canvas_followers
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    ); -- 守门 #13 b 物理删除禁止: 仅 platform_admin

-- canvas_followers schema_isolation policy (per v0.91 §8.3 映射表 5, 14 张新表都含 schema_name 列)
DROP POLICY IF EXISTS canvas_followers_schema_isolation ON canvas_followers;
CREATE POLICY canvas_followers_schema_isolation ON canvas_followers
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

-- canvas_followers platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
DROP POLICY IF EXISTS canvas_followers_platform_admin ON canvas_followers;
CREATE POLICY canvas_followers_platform_admin ON canvas_followers
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;

BEGIN;
-- ==========================================
-- 6. gamify_achievements 表 (per G5 achievement + 守门 #13 c SCD Type 2 (pgpool_version 字段))
-- W/T/M 分类: M
-- 说明: 成就系统 (per G5)
-- ==========================================
CREATE TABLE IF NOT EXISTS gamify_achievements (
    -- 业务字段 (per G5 achievement)
    id                 UUID NOT NULL PRIMARY KEY,
    tenant_id          UUID NOT NULL,
    user_id            UUID NOT NULL,
    achievement_key    TEXT NOT NULL,
    title              TEXT NOT NULL,
    description        TEXT,
    icon_url           TEXT,
    unlocked_at        TIMESTAMPTZ,
    pgpool_version     BIGINT NOT NULL DEFAULT 1,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by         UUID NOT NULL,
    schema_name        TEXT NOT NULL DEFAULT 'public',
    -- 显式主键
    PRIMARY KEY (id)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_gamify_achievements_user_id
    ON gamify_achievements (user_id);
CREATE INDEX IF NOT EXISTS idx_gamify_achievements_achievement_key
    ON gamify_achievements (achievement_key);
CREATE INDEX IF NOT EXISTS idx_gamify_achievements_unlocked_at
    ON gamify_achievements (unlocked_at);
-- 当前 SCD Type 2 "有效" version 视图 (per V0.82 pgpool_version 模式)
CREATE OR REPLACE VIEW v_gamify_achievements_current AS
SELECT DISTINCT ON (tenant_id, id) *
FROM gamify_achievements
ORDER BY tenant_id, id, pgpool_version DESC;


-- ==========================================
-- 6.RLS  RLS 6 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 7 类中跳过 health_visibility (表无 health_status 列, per v0.93 缺口 (d) 修)
-- ==========================================
ALTER TABLE gamify_achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamify_achievements FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- gamify_achievements 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS gamify_achievements_select ON gamify_achievements;
CREATE POLICY gamify_achievements_select ON gamify_achievements
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_achievements_insert ON gamify_achievements;
CREATE POLICY gamify_achievements_insert ON gamify_achievements
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_achievements_update ON gamify_achievements;
CREATE POLICY gamify_achievements_update ON gamify_achievements
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_achievements_delete ON gamify_achievements;
CREATE POLICY gamify_achievements_delete ON gamify_achievements
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    ); -- 守门 #13 b 物理删除禁止: 仅 platform_admin

-- gamify_achievements schema_isolation policy (per v0.91 §8.3 映射表 5, 14 张新表都含 schema_name 列)
DROP POLICY IF EXISTS gamify_achievements_schema_isolation ON gamify_achievements;
CREATE POLICY gamify_achievements_schema_isolation ON gamify_achievements
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

-- gamify_achievements platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
DROP POLICY IF EXISTS gamify_achievements_platform_admin ON gamify_achievements;
CREATE POLICY gamify_achievements_platform_admin ON gamify_achievements
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;

BEGIN;
-- ==========================================
-- 7. gamify_xp_history 表 (per G2 XP + 守门 #13 d T 100% audit WORM append-only (per ADR-0043))
-- W/T/M 分类: T
-- 说明: 经验值累计 (per G2)
-- ==========================================
CREATE TABLE IF NOT EXISTS gamify_xp_history (
    -- 业务字段 (per G2 XP)
    id                 UUID NOT NULL PRIMARY KEY,
    tenant_id          UUID NOT NULL,
    user_id            UUID NOT NULL,
    xp_delta           INTEGER NOT NULL,
    xp_total           INTEGER NOT NULL,
    source             TEXT NOT NULL,
    at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version            BIGINT NOT NULL DEFAULT 1,
    metadata           JSONB DEFAULT '{}'::jsonb,
    schema_name        TEXT NOT NULL DEFAULT 'public',
    -- 显式主键
    PRIMARY KEY (id)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_gamify_xp_history_user_id
    ON gamify_xp_history (user_id);
CREATE INDEX IF NOT EXISTS idx_gamify_xp_history_at
    ON gamify_xp_history (at);
CREATE INDEX IF NOT EXISTS idx_gamify_xp_history_source
    ON gamify_xp_history (source);

-- ==========================================
-- 7.RLS  RLS 6 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 7 类中跳过 health_visibility (表无 health_status 列, per v0.93 缺口 (d) 修)
-- ==========================================
ALTER TABLE gamify_xp_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamify_xp_history FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- gamify_xp_history 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS gamify_xp_history_select ON gamify_xp_history;
CREATE POLICY gamify_xp_history_select ON gamify_xp_history
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_xp_history_insert ON gamify_xp_history;
CREATE POLICY gamify_xp_history_insert ON gamify_xp_history
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_xp_history_update ON gamify_xp_history;
CREATE POLICY gamify_xp_history_update ON gamify_xp_history
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_xp_history_delete ON gamify_xp_history;
CREATE POLICY gamify_xp_history_delete ON gamify_xp_history
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    ); -- 守门 #13 b 物理删除禁止: 仅 platform_admin

-- gamify_xp_history schema_isolation policy (per v0.91 §8.3 映射表 5, 14 张新表都含 schema_name 列)
DROP POLICY IF EXISTS gamify_xp_history_schema_isolation ON gamify_xp_history;
CREATE POLICY gamify_xp_history_schema_isolation ON gamify_xp_history
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

-- gamify_xp_history platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
DROP POLICY IF EXISTS gamify_xp_history_platform_admin ON gamify_xp_history;
CREATE POLICY gamify_xp_history_platform_admin ON gamify_xp_history
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

-- ==========================================
-- 7.WORM  WORM append-only audit trigger (per 守门 #13 d + ADR-0043)
-- 仅允许 INSERT, UPDATE/DELETE 触发异常
-- ==========================================
CREATE OR REPLACE FUNCTION gamify_xp_history_worm_trigger() RETURNS TRIGGER AS $$
BEGIN
    -- WORM append-only: 仅 INSERT 允许, UPDATE/DELETE 触发异常
    IF (TG_OP = 'UPDATE' OR TG_OP = 'DELETE') THEN
        RAISE EXCEPTION 'gamify_xp_history is WORM append-only (per 守门 #13 d + ADR-0043)';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_gamify_xp_history_worm ON gamify_xp_history;
CREATE TRIGGER trg_gamify_xp_history_worm
    BEFORE UPDATE OR DELETE ON gamify_xp_history
    FOR EACH ROW
    EXECUTE FUNCTION gamify_xp_history_worm_trigger();

COMMIT;

BEGIN;
-- ==========================================
-- 8. gamify_level_progress 表 (per G3 level progress + 守门 #13 a 物理删除 + 短 TTL retention_period = 30 days)
-- W/T/M 分类: W
-- 说明: 等级进度 (per G3, retention 30 days)
-- ==========================================
CREATE TABLE IF NOT EXISTS gamify_level_progress (
    -- 业务字段 (per G3 level progress)
    id                 UUID NOT NULL PRIMARY KEY,
    tenant_id          UUID NOT NULL,
    user_id            UUID NOT NULL,
    level_id           UUID NOT NULL,
    xp_in_level        INTEGER NOT NULL DEFAULT 0,
    xp_needed_next     INTEGER NOT NULL,
    last_updated       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    schema_name        TEXT NOT NULL DEFAULT 'public',
    -- 显式主键
    PRIMARY KEY (id)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_gamify_level_progress_user_id
    ON gamify_level_progress (user_id);
CREATE INDEX IF NOT EXISTS idx_gamify_level_progress_level_id
    ON gamify_level_progress (level_id);
CREATE INDEX IF NOT EXISTS idx_gamify_level_progress_last_updated
    ON gamify_level_progress (last_updated);

-- ==========================================
-- 8.RLS  RLS 6 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 7 类中跳过 health_visibility (表无 health_status 列, per v0.93 缺口 (d) 修)
-- ==========================================
ALTER TABLE gamify_level_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamify_level_progress FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- gamify_level_progress 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS gamify_level_progress_select ON gamify_level_progress;
CREATE POLICY gamify_level_progress_select ON gamify_level_progress
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_level_progress_insert ON gamify_level_progress;
CREATE POLICY gamify_level_progress_insert ON gamify_level_progress
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_level_progress_update ON gamify_level_progress;
CREATE POLICY gamify_level_progress_update ON gamify_level_progress
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_level_progress_delete ON gamify_level_progress;
CREATE POLICY gamify_level_progress_delete ON gamify_level_progress
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    ); -- 守门 #13 b 物理删除禁止: 仅 platform_admin

-- gamify_level_progress schema_isolation policy (per v0.91 §8.3 映射表 5, 14 张新表都含 schema_name 列)
DROP POLICY IF EXISTS gamify_level_progress_schema_isolation ON gamify_level_progress;
CREATE POLICY gamify_level_progress_schema_isolation ON gamify_level_progress
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

-- gamify_level_progress platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
DROP POLICY IF EXISTS gamify_level_progress_platform_admin ON gamify_level_progress;
CREATE POLICY gamify_level_progress_platform_admin ON gamify_level_progress
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;

BEGIN;
-- ==========================================
-- 9. gamify_rewards 表 (per G7 rewards + 守门 #13 c SCD Type 2 (pgpool_version 字段))
-- W/T/M 分类: M
-- 说明: 奖励 (per G7)
-- ==========================================
CREATE TABLE IF NOT EXISTS gamify_rewards (
    -- 业务字段 (per G7 rewards)
    id                 UUID NOT NULL PRIMARY KEY,
    tenant_id          UUID NOT NULL,
    user_id            UUID NOT NULL,
    reward_key         TEXT NOT NULL,
    title              TEXT NOT NULL,
    description        TEXT,
    cost_xp            INTEGER NOT NULL CHECK (cost_xp >= 0),
    status             TEXT NOT NULL CHECK (status IN ('Available', 'Redeemed', 'Expired')),
    pgpool_version     BIGINT NOT NULL DEFAULT 1,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    schema_name        TEXT NOT NULL DEFAULT 'public',
    -- 显式主键
    PRIMARY KEY (id)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_gamify_rewards_user_id
    ON gamify_rewards (user_id);
CREATE INDEX IF NOT EXISTS idx_gamify_rewards_reward_key
    ON gamify_rewards (reward_key);
CREATE INDEX IF NOT EXISTS idx_gamify_rewards_status
    ON gamify_rewards (status);
CREATE INDEX IF NOT EXISTS idx_gamify_rewards_cost_xp
    ON gamify_rewards (cost_xp);
-- 当前 SCD Type 2 "有效" version 视图 (per V0.82 pgpool_version 模式)
CREATE OR REPLACE VIEW v_gamify_rewards_current AS
SELECT DISTINCT ON (tenant_id, id) *
FROM gamify_rewards
ORDER BY tenant_id, id, pgpool_version DESC;


-- ==========================================
-- 9.RLS  RLS 6 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 7 类中跳过 health_visibility (表无 health_status 列, per v0.93 缺口 (d) 修)
-- ==========================================
ALTER TABLE gamify_rewards ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamify_rewards FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- gamify_rewards 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS gamify_rewards_select ON gamify_rewards;
CREATE POLICY gamify_rewards_select ON gamify_rewards
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_rewards_insert ON gamify_rewards;
CREATE POLICY gamify_rewards_insert ON gamify_rewards
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_rewards_update ON gamify_rewards;
CREATE POLICY gamify_rewards_update ON gamify_rewards
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_rewards_delete ON gamify_rewards;
CREATE POLICY gamify_rewards_delete ON gamify_rewards
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    ); -- 守门 #13 b 物理删除禁止: 仅 platform_admin

-- gamify_rewards schema_isolation policy (per v0.91 §8.3 映射表 5, 14 张新表都含 schema_name 列)
DROP POLICY IF EXISTS gamify_rewards_schema_isolation ON gamify_rewards;
CREATE POLICY gamify_rewards_schema_isolation ON gamify_rewards
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

-- gamify_rewards platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
DROP POLICY IF EXISTS gamify_rewards_platform_admin ON gamify_rewards;
CREATE POLICY gamify_rewards_platform_admin ON gamify_rewards
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;

BEGIN;
-- ==========================================
-- 10. gamify_leaderboards 表 (per G6 leaderboard + 守门 #13 c SCD Type 2 (pgpool_version 字段))
-- W/T/M 分类: M
-- 说明: 排行榜 (per G6)
-- ==========================================
CREATE TABLE IF NOT EXISTS gamify_leaderboards (
    -- 业务字段 (per G6 leaderboard)
    id                 UUID NOT NULL PRIMARY KEY,
    tenant_id          UUID NOT NULL,
    board_key          TEXT NOT NULL,
    user_id            UUID NOT NULL,
    rank               INTEGER NOT NULL CHECK (rank > 0),
    score              INTEGER NOT NULL CHECK (score >= 0),
    period             TEXT NOT NULL CHECK (period IN ('Daily', 'Weekly', 'Monthly', 'AllTime')),
    pgpool_version     BIGINT NOT NULL DEFAULT 1,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    schema_name        TEXT NOT NULL DEFAULT 'public',
    -- 显式主键
    PRIMARY KEY (id)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_gamify_leaderboards_board_key
    ON gamify_leaderboards (board_key);
CREATE INDEX IF NOT EXISTS idx_gamify_leaderboards_user_id
    ON gamify_leaderboards (user_id);
CREATE INDEX IF NOT EXISTS idx_gamify_leaderboards_rank
    ON gamify_leaderboards (rank);
CREATE INDEX IF NOT EXISTS idx_gamify_leaderboards_score
    ON gamify_leaderboards (score);
CREATE INDEX IF NOT EXISTS idx_gamify_leaderboards_period
    ON gamify_leaderboards (period);
-- 当前 SCD Type 2 "有效" version 视图 (per V0.82 pgpool_version 模式)
CREATE OR REPLACE VIEW v_gamify_leaderboards_current AS
SELECT DISTINCT ON (tenant_id, id) *
FROM gamify_leaderboards
ORDER BY tenant_id, id, pgpool_version DESC;


-- ==========================================
-- 10.RLS  RLS 6 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 7 类中跳过 health_visibility (表无 health_status 列, per v0.93 缺口 (d) 修)
-- ==========================================
ALTER TABLE gamify_leaderboards ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamify_leaderboards FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- gamify_leaderboards 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS gamify_leaderboards_select ON gamify_leaderboards;
CREATE POLICY gamify_leaderboards_select ON gamify_leaderboards
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_leaderboards_insert ON gamify_leaderboards;
CREATE POLICY gamify_leaderboards_insert ON gamify_leaderboards
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_leaderboards_update ON gamify_leaderboards;
CREATE POLICY gamify_leaderboards_update ON gamify_leaderboards
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_leaderboards_delete ON gamify_leaderboards;
CREATE POLICY gamify_leaderboards_delete ON gamify_leaderboards
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    ); -- 守门 #13 b 物理删除禁止: 仅 platform_admin

-- gamify_leaderboards schema_isolation policy (per v0.91 §8.3 映射表 5, 14 张新表都含 schema_name 列)
DROP POLICY IF EXISTS gamify_leaderboards_schema_isolation ON gamify_leaderboards;
CREATE POLICY gamify_leaderboards_schema_isolation ON gamify_leaderboards
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

-- gamify_leaderboards platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
DROP POLICY IF EXISTS gamify_leaderboards_platform_admin ON gamify_leaderboards;
CREATE POLICY gamify_leaderboards_platform_admin ON gamify_leaderboards
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;

BEGIN;
-- ==========================================
-- 11. gamify_avatar_customization 表 (per G4 avatar customization + 守门 #13 c SCD Type 2 (pgpool_version 字段))
-- W/T/M 分类: M
-- 说明: 头像定制 (per G4)
-- ==========================================
CREATE TABLE IF NOT EXISTS gamify_avatar_customization (
    -- 业务字段 (per G4 avatar customization)
    id                 UUID NOT NULL PRIMARY KEY,
    tenant_id          UUID NOT NULL,
    user_id            UUID NOT NULL,
    slot               TEXT NOT NULL CHECK (slot IN ('Hat', 'Body', 'Background', 'Accessory', 'Pet')),
    asset_id           UUID,
    color_hex          TEXT CHECK (color_hex IS NULL OR color_hex ~ '^#[0-9A-Fa-f]{6}$'),
    is_equipped        BOOLEAN NOT NULL DEFAULT false,
    pgpool_version     BIGINT NOT NULL DEFAULT 1,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    schema_name        TEXT NOT NULL DEFAULT 'public',
    -- 显式主键
    PRIMARY KEY (id)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_gamify_avatar_customization_user_id
    ON gamify_avatar_customization (user_id);
CREATE INDEX IF NOT EXISTS idx_gamify_avatar_customization_slot
    ON gamify_avatar_customization (slot);
CREATE INDEX IF NOT EXISTS idx_gamify_avatar_customization_is_equipped
    ON gamify_avatar_customization (is_equipped);
-- 当前 SCD Type 2 "有效" version 视图 (per V0.82 pgpool_version 模式)
CREATE OR REPLACE VIEW v_gamify_avatar_customization_current AS
SELECT DISTINCT ON (tenant_id, id) *
FROM gamify_avatar_customization
ORDER BY tenant_id, id, pgpool_version DESC;


-- ==========================================
-- 11.RLS  RLS 6 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 7 类中跳过 health_visibility (表无 health_status 列, per v0.93 缺口 (d) 修)
-- ==========================================
ALTER TABLE gamify_avatar_customization ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamify_avatar_customization FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- gamify_avatar_customization 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS gamify_avatar_customization_select ON gamify_avatar_customization;
CREATE POLICY gamify_avatar_customization_select ON gamify_avatar_customization
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_avatar_customization_insert ON gamify_avatar_customization;
CREATE POLICY gamify_avatar_customization_insert ON gamify_avatar_customization
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_avatar_customization_update ON gamify_avatar_customization;
CREATE POLICY gamify_avatar_customization_update ON gamify_avatar_customization
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_avatar_customization_delete ON gamify_avatar_customization;
CREATE POLICY gamify_avatar_customization_delete ON gamify_avatar_customization
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    ); -- 守门 #13 b 物理删除禁止: 仅 platform_admin

-- gamify_avatar_customization schema_isolation policy (per v0.91 §8.3 映射表 5, 14 张新表都含 schema_name 列)
DROP POLICY IF EXISTS gamify_avatar_customization_schema_isolation ON gamify_avatar_customization;
CREATE POLICY gamify_avatar_customization_schema_isolation ON gamify_avatar_customization
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

-- gamify_avatar_customization platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
DROP POLICY IF EXISTS gamify_avatar_customization_platform_admin ON gamify_avatar_customization;
CREATE POLICY gamify_avatar_customization_platform_admin ON gamify_avatar_customization
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;

BEGIN;
-- ==========================================
-- 12. gamify_vote_audit 表 (per G8 vote audit + 守门 #13 d T 100% audit WORM append-only (per ADR-0043))
-- W/T/M 分类: T
-- 说明: 投票审计 (per G8)
-- ==========================================
CREATE TABLE IF NOT EXISTS gamify_vote_audit (
    -- 业务字段 (per G8 vote audit)
    id                 UUID NOT NULL PRIMARY KEY,
    tenant_id          UUID NOT NULL,
    vote_id            UUID NOT NULL,
    user_id            UUID NOT NULL,
    action             TEXT NOT NULL CHECK (action IN ('cast', 'change', 'retract')),
    at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version            BIGINT NOT NULL DEFAULT 1,
    schema_name        TEXT NOT NULL DEFAULT 'public',
    -- 显式主键
    PRIMARY KEY (id)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_gamify_vote_audit_vote_id
    ON gamify_vote_audit (vote_id);
CREATE INDEX IF NOT EXISTS idx_gamify_vote_audit_user_id
    ON gamify_vote_audit (user_id);
CREATE INDEX IF NOT EXISTS idx_gamify_vote_audit_at
    ON gamify_vote_audit (at);
CREATE INDEX IF NOT EXISTS idx_gamify_vote_audit_action
    ON gamify_vote_audit (action);

-- ==========================================
-- 12.RLS  RLS 6 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 7 类中跳过 health_visibility (表无 health_status 列, per v0.93 缺口 (d) 修)
-- ==========================================
ALTER TABLE gamify_vote_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamify_vote_audit FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- gamify_vote_audit 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS gamify_vote_audit_select ON gamify_vote_audit;
CREATE POLICY gamify_vote_audit_select ON gamify_vote_audit
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_vote_audit_insert ON gamify_vote_audit;
CREATE POLICY gamify_vote_audit_insert ON gamify_vote_audit
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_vote_audit_update ON gamify_vote_audit;
CREATE POLICY gamify_vote_audit_update ON gamify_vote_audit
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_vote_audit_delete ON gamify_vote_audit;
CREATE POLICY gamify_vote_audit_delete ON gamify_vote_audit
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    ); -- 守门 #13 b 物理删除禁止: 仅 platform_admin

-- gamify_vote_audit schema_isolation policy (per v0.91 §8.3 映射表 5, 14 张新表都含 schema_name 列)
DROP POLICY IF EXISTS gamify_vote_audit_schema_isolation ON gamify_vote_audit;
CREATE POLICY gamify_vote_audit_schema_isolation ON gamify_vote_audit
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

-- gamify_vote_audit platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
DROP POLICY IF EXISTS gamify_vote_audit_platform_admin ON gamify_vote_audit;
CREATE POLICY gamify_vote_audit_platform_admin ON gamify_vote_audit
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

-- ==========================================
-- 12.WORM  WORM append-only audit trigger (per 守门 #13 d + ADR-0043)
-- 仅允许 INSERT, UPDATE/DELETE 触发异常
-- ==========================================
CREATE OR REPLACE FUNCTION gamify_vote_worm_trigger() RETURNS TRIGGER AS $$
BEGIN
    -- WORM append-only: 仅 INSERT 允许, UPDATE/DELETE 触发异常
    IF (TG_OP = 'UPDATE' OR TG_OP = 'DELETE') THEN
        RAISE EXCEPTION 'gamify_vote_audit is WORM append-only (per 守门 #13 d + ADR-0043)';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_gamify_vote_audit_worm ON gamify_vote_audit;
CREATE TRIGGER trg_gamify_vote_audit_worm
    BEFORE UPDATE OR DELETE ON gamify_vote_audit
    FOR EACH ROW
    EXECUTE FUNCTION gamify_vote_worm_trigger();

COMMIT;

BEGIN;
-- ==========================================
-- 13. gamify_sticky_note_audit 表 (per G9 sticky note audit + 守门 #13 d T 100% audit WORM append-only (per ADR-0043))
-- W/T/M 分类: T
-- 说明: Sticky note 审计 (per G9)
-- ==========================================
CREATE TABLE IF NOT EXISTS gamify_sticky_note_audit (
    -- 业务字段 (per G9 sticky note audit)
    id                 UUID NOT NULL PRIMARY KEY,
    tenant_id          UUID NOT NULL,
    sticky_note_id     UUID NOT NULL,
    user_id            UUID NOT NULL,
    action             TEXT NOT NULL CHECK (action IN ('create', 'update', 'delete', 'pin', 'unpin')),
    at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version            BIGINT NOT NULL DEFAULT 1,
    schema_name        TEXT NOT NULL DEFAULT 'public',
    -- 显式主键
    PRIMARY KEY (id)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_gamify_sticky_note_audit_sticky_note_id
    ON gamify_sticky_note_audit (sticky_note_id);
CREATE INDEX IF NOT EXISTS idx_gamify_sticky_note_audit_user_id
    ON gamify_sticky_note_audit (user_id);
CREATE INDEX IF NOT EXISTS idx_gamify_sticky_note_audit_at
    ON gamify_sticky_note_audit (at);
CREATE INDEX IF NOT EXISTS idx_gamify_sticky_note_audit_action
    ON gamify_sticky_note_audit (action);

-- ==========================================
-- 13.RLS  RLS 6 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 7 类中跳过 health_visibility (表无 health_status 列, per v0.93 缺口 (d) 修)
-- ==========================================
ALTER TABLE gamify_sticky_note_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamify_sticky_note_audit FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- gamify_sticky_note_audit 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS gamify_sticky_note_audit_select ON gamify_sticky_note_audit;
CREATE POLICY gamify_sticky_note_audit_select ON gamify_sticky_note_audit
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_sticky_note_audit_insert ON gamify_sticky_note_audit;
CREATE POLICY gamify_sticky_note_audit_insert ON gamify_sticky_note_audit
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_sticky_note_audit_update ON gamify_sticky_note_audit;
CREATE POLICY gamify_sticky_note_audit_update ON gamify_sticky_note_audit
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_sticky_note_audit_delete ON gamify_sticky_note_audit;
CREATE POLICY gamify_sticky_note_audit_delete ON gamify_sticky_note_audit
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    ); -- 守门 #13 b 物理删除禁止: 仅 platform_admin

-- gamify_sticky_note_audit schema_isolation policy (per v0.91 §8.3 映射表 5, 14 张新表都含 schema_name 列)
DROP POLICY IF EXISTS gamify_sticky_note_audit_schema_isolation ON gamify_sticky_note_audit;
CREATE POLICY gamify_sticky_note_audit_schema_isolation ON gamify_sticky_note_audit
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

-- gamify_sticky_note_audit platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
DROP POLICY IF EXISTS gamify_sticky_note_audit_platform_admin ON gamify_sticky_note_audit;
CREATE POLICY gamify_sticky_note_audit_platform_admin ON gamify_sticky_note_audit
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

-- ==========================================
-- 13.WORM  WORM append-only audit trigger (per 守门 #13 d + ADR-0043)
-- 仅允许 INSERT, UPDATE/DELETE 触发异常
-- ==========================================
CREATE OR REPLACE FUNCTION gamify_sticky_note_worm_trigger() RETURNS TRIGGER AS $$
BEGIN
    -- WORM append-only: 仅 INSERT 允许, UPDATE/DELETE 触发异常
    IF (TG_OP = 'UPDATE' OR TG_OP = 'DELETE') THEN
        RAISE EXCEPTION 'gamify_sticky_note_audit is WORM append-only (per 守门 #13 d + ADR-0043)';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_gamify_sticky_note_audit_worm ON gamify_sticky_note_audit;
CREATE TRIGGER trg_gamify_sticky_note_audit_worm
    BEFORE UPDATE OR DELETE ON gamify_sticky_note_audit
    FOR EACH ROW
    EXECUTE FUNCTION gamify_sticky_note_worm_trigger();

COMMIT;

BEGIN;
-- ==========================================
-- 14. gamify_confetti_audit 表 (per G10 confetti audit + 守门 #13 d T 100% audit WORM append-only (per ADR-0043))
-- W/T/M 分类: T
-- 说明: 撒花审计 (per G10)
-- ==========================================
CREATE TABLE IF NOT EXISTS gamify_confetti_audit (
    -- 业务字段 (per G10 confetti audit)
    id                 UUID NOT NULL PRIMARY KEY,
    tenant_id          UUID NOT NULL,
    confetti_id        UUID NOT NULL,
    user_id            UUID NOT NULL,
    action             TEXT NOT NULL CHECK (action IN ('trigger', 'burst', 'complete')),
    at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version            BIGINT NOT NULL DEFAULT 1,
    schema_name        TEXT NOT NULL DEFAULT 'public',
    -- 显式主键
    PRIMARY KEY (id)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_gamify_confetti_audit_confetti_id
    ON gamify_confetti_audit (confetti_id);
CREATE INDEX IF NOT EXISTS idx_gamify_confetti_audit_user_id
    ON gamify_confetti_audit (user_id);
CREATE INDEX IF NOT EXISTS idx_gamify_confetti_audit_at
    ON gamify_confetti_audit (at);
CREATE INDEX IF NOT EXISTS idx_gamify_confetti_audit_action
    ON gamify_confetti_audit (action);

-- ==========================================
-- 14.RLS  RLS 6 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 7 类中跳过 health_visibility (表无 health_status 列, per v0.93 缺口 (d) 修)
-- ==========================================
ALTER TABLE gamify_confetti_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamify_confetti_audit FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- gamify_confetti_audit 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS gamify_confetti_audit_select ON gamify_confetti_audit;
CREATE POLICY gamify_confetti_audit_select ON gamify_confetti_audit
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_confetti_audit_insert ON gamify_confetti_audit;
CREATE POLICY gamify_confetti_audit_insert ON gamify_confetti_audit
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_confetti_audit_update ON gamify_confetti_audit;
CREATE POLICY gamify_confetti_audit_update ON gamify_confetti_audit
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS gamify_confetti_audit_delete ON gamify_confetti_audit;
CREATE POLICY gamify_confetti_audit_delete ON gamify_confetti_audit
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    ); -- 守门 #13 b 物理删除禁止: 仅 platform_admin

-- gamify_confetti_audit schema_isolation policy (per v0.91 §8.3 映射表 5, 14 张新表都含 schema_name 列)
DROP POLICY IF EXISTS gamify_confetti_audit_schema_isolation ON gamify_confetti_audit;
CREATE POLICY gamify_confetti_audit_schema_isolation ON gamify_confetti_audit
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

-- gamify_confetti_audit platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
DROP POLICY IF EXISTS gamify_confetti_audit_platform_admin ON gamify_confetti_audit;
CREATE POLICY gamify_confetti_audit_platform_admin ON gamify_confetti_audit
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

-- ==========================================
-- 14.WORM  WORM append-only audit trigger (per 守门 #13 d + ADR-0043)
-- 仅允许 INSERT, UPDATE/DELETE 触发异常
-- ==========================================
CREATE OR REPLACE FUNCTION gamify_confetti_worm_trigger() RETURNS TRIGGER AS $$
BEGIN
    -- WORM append-only: 仅 INSERT 允许, UPDATE/DELETE 触发异常
    IF (TG_OP = 'UPDATE' OR TG_OP = 'DELETE') THEN
        RAISE EXCEPTION 'gamify_confetti_audit is WORM append-only (per 守门 #13 d + ADR-0043)';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_gamify_confetti_audit_worm ON gamify_confetti_audit;
CREATE TRIGGER trg_gamify_confetti_audit_worm
    BEFORE UPDATE OR DELETE ON gamify_confetti_audit
    FOR EACH ROW
    EXECUTE FUNCTION gamify_confetti_worm_trigger();

COMMIT;

COMMIT;
