-- 2026-09-10-rls-7policy-all-tables.sql (auto-generated by scripts/sql/rls_7_policy_gen.py)
-- v0.92 P0-4 Stage 3.8 = 7 类 RLS policy 模板生成器 (per v0.91 命名)
-- (per v0.91 §3 已知缺口 (a) 'P3-D.6 14+15 张表落地时, 7 类 policy 模板需走 v0.91 命名' 跨 session 续做)
--
-- 守门 #13 a 100% RLS: ENABLE + FORCE
-- 守门 #13 b 物理删除禁止: 4 类 CRUD delete 仅 platform_admin
-- 守门 #13 c M SCD Type 2: 跟 v0.82 pgpool_version 字段协同
-- 守门 #13 d T 100% audit: audit trigger 跨 RLS 写 (per ADR-0043 WORM)
-- 守门 #19 v19 批量改: 1 脚本 + N 输出, 走幂等
-- 守门 #1 禁回溯叙事: 不重写 v0.87 已有 tenant_pools DDL, 仅生成新表 DDL
-- 守门 #11 缺标比错标: P0-4 阶段只生成模板, P2 阶段 worker 子代理 + testcontainers 实测

BEGIN;


-- ==========================================
-- ops_metrics_config 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- ops_metrics_config RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE ops_metrics_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE ops_metrics_config FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- ops_metrics_config 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY ops_metrics_config_select ON ops_metrics_config
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY ops_metrics_config_insert ON ops_metrics_config
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY ops_metrics_config_update ON ops_metrics_config
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY ops_metrics_config_delete ON ops_metrics_config
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ops_metrics_config schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- ops_metrics_config platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY ops_metrics_config_platform_admin ON ops_metrics_config
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- ops_cluster_action_log 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- ops_cluster_action_log RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE ops_cluster_action_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE ops_cluster_action_log FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- ops_cluster_action_log 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY ops_cluster_action_log_select ON ops_cluster_action_log
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY ops_cluster_action_log_insert ON ops_cluster_action_log
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY ops_cluster_action_log_update ON ops_cluster_action_log
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY ops_cluster_action_log_delete ON ops_cluster_action_log
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ops_cluster_action_log schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- ops_cluster_action_log platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY ops_cluster_action_log_platform_admin ON ops_cluster_action_log
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- ops_helm_release_state 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- ops_helm_release_state RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE ops_helm_release_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE ops_helm_release_state FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- ops_helm_release_state 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY ops_helm_release_state_select ON ops_helm_release_state
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY ops_helm_release_state_insert ON ops_helm_release_state
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY ops_helm_release_state_update ON ops_helm_release_state
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY ops_helm_release_state_delete ON ops_helm_release_state
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ops_helm_release_state schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- ops_helm_release_state platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY ops_helm_release_state_platform_admin ON ops_helm_release_state
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- ops_log_entry 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- ops_log_entry RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE ops_log_entry ENABLE ROW LEVEL SECURITY;
ALTER TABLE ops_log_entry FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- ops_log_entry 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY ops_log_entry_select ON ops_log_entry
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY ops_log_entry_insert ON ops_log_entry
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY ops_log_entry_update ON ops_log_entry
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY ops_log_entry_delete ON ops_log_entry
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ops_log_entry schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- ops_log_entry platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY ops_log_entry_platform_admin ON ops_log_entry
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- ops_log_analysis 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- ops_log_analysis RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE ops_log_analysis ENABLE ROW LEVEL SECURITY;
ALTER TABLE ops_log_analysis FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- ops_log_analysis 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY ops_log_analysis_select ON ops_log_analysis
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY ops_log_analysis_insert ON ops_log_analysis
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY ops_log_analysis_update ON ops_log_analysis
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY ops_log_analysis_delete ON ops_log_analysis
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ops_log_analysis schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- ops_log_analysis platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY ops_log_analysis_platform_admin ON ops_log_analysis
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- ops_log_query_log 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- ops_log_query_log RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE ops_log_query_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE ops_log_query_log FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- ops_log_query_log 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY ops_log_query_log_select ON ops_log_query_log
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY ops_log_query_log_insert ON ops_log_query_log
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY ops_log_query_log_update ON ops_log_query_log
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY ops_log_query_log_delete ON ops_log_query_log
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ops_log_query_log schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- ops_log_query_log platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY ops_log_query_log_platform_admin ON ops_log_query_log
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- oauth_clients 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- oauth_clients RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE oauth_clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE oauth_clients FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- oauth_clients 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY oauth_clients_select ON oauth_clients
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY oauth_clients_insert ON oauth_clients
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY oauth_clients_update ON oauth_clients
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY oauth_clients_delete ON oauth_clients
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- oauth_clients schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- oauth_clients platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY oauth_clients_platform_admin ON oauth_clients
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- oauth_authorization_codes 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- oauth_authorization_codes RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE oauth_authorization_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE oauth_authorization_codes FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- oauth_authorization_codes 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY oauth_authorization_codes_select ON oauth_authorization_codes
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY oauth_authorization_codes_insert ON oauth_authorization_codes
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY oauth_authorization_codes_update ON oauth_authorization_codes
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY oauth_authorization_codes_delete ON oauth_authorization_codes
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- oauth_authorization_codes schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- oauth_authorization_codes platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY oauth_authorization_codes_platform_admin ON oauth_authorization_codes
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- oauth_access_tokens 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- oauth_access_tokens RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE oauth_access_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE oauth_access_tokens FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- oauth_access_tokens 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY oauth_access_tokens_select ON oauth_access_tokens
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY oauth_access_tokens_insert ON oauth_access_tokens
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY oauth_access_tokens_update ON oauth_access_tokens
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY oauth_access_tokens_delete ON oauth_access_tokens
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- oauth_access_tokens schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- oauth_access_tokens platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY oauth_access_tokens_platform_admin ON oauth_access_tokens
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- oauth_refresh_tokens 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- oauth_refresh_tokens RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE oauth_refresh_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE oauth_refresh_tokens FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- oauth_refresh_tokens 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY oauth_refresh_tokens_select ON oauth_refresh_tokens
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY oauth_refresh_tokens_insert ON oauth_refresh_tokens
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY oauth_refresh_tokens_update ON oauth_refresh_tokens
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY oauth_refresh_tokens_delete ON oauth_refresh_tokens
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- oauth_refresh_tokens schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- oauth_refresh_tokens platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY oauth_refresh_tokens_platform_admin ON oauth_refresh_tokens
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- tenant_pools 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- tenant_pools RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE tenant_pools ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_pools FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- tenant_pools 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY tenant_pools_select ON tenant_pools
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY tenant_pools_insert ON tenant_pools
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY tenant_pools_update ON tenant_pools
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY tenant_pools_delete ON tenant_pools
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- tenant_pools schema isolation (per v0.91 §8.3 映射表 5)
CREATE POLICY tenant_pools_schema_isolation ON tenant_pools
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

-- tenant_pools platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY tenant_pools_platform_admin ON tenant_pools
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

-- tenant_pools health_status 派生 visibility (per v0.91 §8.3 映射表 7, 5 status OR 合并)
CREATE POLICY tenant_pools_health_visibility ON tenant_pools
    FOR SELECT
    USING (
        (health_status = 'Healthy' AND current_setting('app.can_see_healthy', true) = 'true')
        OR (health_status = 'Degraded' AND current_setting('app.can_see_degraded', true) = 'true')
        OR (health_status = 'Down' AND current_setting('app.can_see_down', true) = 'true')
        OR (health_status = 'Deleted' AND current_setting('app.can_see_deleted', true) = 'true')
        OR (health_status = 'NotChecked' AND current_setting('app.can_see_notchecked', true) = 'true')
        OR current_setting('app.is_admin', true) = 'true'
    );


-- ==========================================
-- agent_sessions 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- agent_sessions RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE agent_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_sessions FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- agent_sessions 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY agent_sessions_select ON agent_sessions
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY agent_sessions_insert ON agent_sessions
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY agent_sessions_update ON agent_sessions
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY agent_sessions_delete ON agent_sessions
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- agent_sessions schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- agent_sessions platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY agent_sessions_platform_admin ON agent_sessions
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- agent_policies 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- agent_policies RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE agent_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_policies FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- agent_policies 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY agent_policies_select ON agent_policies
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY agent_policies_insert ON agent_policies
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY agent_policies_update ON agent_policies
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY agent_policies_delete ON agent_policies
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- agent_policies schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- agent_policies platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY agent_policies_platform_admin ON agent_policies
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- agent_actions 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- agent_actions RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE agent_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_actions FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- agent_actions 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY agent_actions_select ON agent_actions
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY agent_actions_insert ON agent_actions
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY agent_actions_update ON agent_actions
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY agent_actions_delete ON agent_actions
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- agent_actions schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- agent_actions platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY agent_actions_platform_admin ON agent_actions
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- agent_relationships 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- agent_relationships RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE agent_relationships ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_relationships FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- agent_relationships 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY agent_relationships_select ON agent_relationships
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY agent_relationships_insert ON agent_relationships
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY agent_relationships_update ON agent_relationships
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY agent_relationships_delete ON agent_relationships
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- agent_relationships schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- agent_relationships platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY agent_relationships_platform_admin ON agent_relationships
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- agent_trust_scores 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- agent_trust_scores RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE agent_trust_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_trust_scores FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- agent_trust_scores 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY agent_trust_scores_select ON agent_trust_scores
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY agent_trust_scores_insert ON agent_trust_scores
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY agent_trust_scores_update ON agent_trust_scores
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY agent_trust_scores_delete ON agent_trust_scores
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- agent_trust_scores schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- agent_trust_scores platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY agent_trust_scores_platform_admin ON agent_trust_scores
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- canvas_elements 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- canvas_elements RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE canvas_elements ENABLE ROW LEVEL SECURITY;
ALTER TABLE canvas_elements FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- canvas_elements 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY canvas_elements_select ON canvas_elements
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY canvas_elements_insert ON canvas_elements
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY canvas_elements_update ON canvas_elements
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY canvas_elements_delete ON canvas_elements
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- canvas_elements schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- canvas_elements platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY canvas_elements_platform_admin ON canvas_elements
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- canvas_multi_user_audit 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- canvas_multi_user_audit RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE canvas_multi_user_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE canvas_multi_user_audit FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- canvas_multi_user_audit 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY canvas_multi_user_audit_select ON canvas_multi_user_audit
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY canvas_multi_user_audit_insert ON canvas_multi_user_audit
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY canvas_multi_user_audit_update ON canvas_multi_user_audit
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY canvas_multi_user_audit_delete ON canvas_multi_user_audit
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- canvas_multi_user_audit schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- canvas_multi_user_audit platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY canvas_multi_user_audit_platform_admin ON canvas_multi_user_audit
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- canvas_reactions 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- canvas_reactions RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE canvas_reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE canvas_reactions FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- canvas_reactions 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY canvas_reactions_select ON canvas_reactions
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY canvas_reactions_insert ON canvas_reactions
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY canvas_reactions_update ON canvas_reactions
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY canvas_reactions_delete ON canvas_reactions
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- canvas_reactions schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- canvas_reactions platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY canvas_reactions_platform_admin ON canvas_reactions
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- canvas_comments 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- canvas_comments RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE canvas_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE canvas_comments FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- canvas_comments 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY canvas_comments_select ON canvas_comments
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY canvas_comments_insert ON canvas_comments
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY canvas_comments_update ON canvas_comments
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY canvas_comments_delete ON canvas_comments
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- canvas_comments schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- canvas_comments platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY canvas_comments_platform_admin ON canvas_comments
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- gamify_avatars 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- gamify_avatars RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE gamify_avatars ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamify_avatars FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- gamify_avatars 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY gamify_avatars_select ON gamify_avatars
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY gamify_avatars_insert ON gamify_avatars
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY gamify_avatars_update ON gamify_avatars
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY gamify_avatars_delete ON gamify_avatars
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- gamify_avatars schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- gamify_avatars platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY gamify_avatars_platform_admin ON gamify_avatars
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- gamify_levels 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- gamify_levels RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE gamify_levels ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamify_levels FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- gamify_levels 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY gamify_levels_select ON gamify_levels
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY gamify_levels_insert ON gamify_levels
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY gamify_levels_update ON gamify_levels
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY gamify_levels_delete ON gamify_levels
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- gamify_levels schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- gamify_levels platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY gamify_levels_platform_admin ON gamify_levels
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- gamify_sticky_notes 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- gamify_sticky_notes RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE gamify_sticky_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamify_sticky_notes FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- gamify_sticky_notes 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY gamify_sticky_notes_select ON gamify_sticky_notes
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY gamify_sticky_notes_insert ON gamify_sticky_notes
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY gamify_sticky_notes_update ON gamify_sticky_notes
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY gamify_sticky_notes_delete ON gamify_sticky_notes
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- gamify_sticky_notes schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- gamify_sticky_notes platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY gamify_sticky_notes_platform_admin ON gamify_sticky_notes
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- gamify_confetti 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- gamify_confetti RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE gamify_confetti ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamify_confetti FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- gamify_confetti 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY gamify_confetti_select ON gamify_confetti
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY gamify_confetti_insert ON gamify_confetti
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY gamify_confetti_update ON gamify_confetti
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY gamify_confetti_delete ON gamify_confetti
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- gamify_confetti schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- gamify_confetti platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY gamify_confetti_platform_admin ON gamify_confetti
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- gamify_votes 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- gamify_votes RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE gamify_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamify_votes FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- gamify_votes 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY gamify_votes_select ON gamify_votes
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY gamify_votes_insert ON gamify_votes
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY gamify_votes_update ON gamify_votes
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY gamify_votes_delete ON gamify_votes
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- gamify_votes schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- gamify_votes platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY gamify_votes_platform_admin ON gamify_votes
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- gamify_streaks 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- gamify_streaks RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE gamify_streaks ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamify_streaks FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- gamify_streaks 4 类 CRUD policy (per v0.91 §8.3 映射表 1-4)
CREATE POLICY gamify_streaks_select ON gamify_streaks
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY gamify_streaks_insert ON gamify_streaks
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY gamify_streaks_update ON gamify_streaks
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

CREATE POLICY gamify_streaks_delete ON gamify_streaks
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- gamify_streaks schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- gamify_streaks platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS)
CREATE POLICY gamify_streaks_platform_admin ON gamify_streaks
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


COMMIT;
