-- 2026-09-10-rls-7policy-all-tables.sql (auto-generated by scripts/sql/rls_7_policy_gen.py)
-- v0.92 P0-4 Stage 3.8 = 7 类 RLS policy 模板生成器 (per v0.91 命名)
-- (per v0.91 §3 已知缺口 (a) 'P3-D.6 14+15 张表落地时, 7 类 policy 模板需走 v0.91 命名' 跨 session 续做)
--
-- 守门 #13 a 100% RLS: ENABLE + FORCE
-- 守门 #13 b 物理删除禁止: 4 类 CRUD delete 仅 platform_admin
-- 守门 #13 c M SCD Type 2: 跟 v0.82 pgpool_version 字段协同
-- 守门 #13 d T 100% audit: audit trigger 跨 RLS 写 (per ADR-0043 WORM)
-- 守门 #19 v19 批量改: 1 脚本 + N 输出, 走幂等
-- 守门 #1 禁回溯叙事: 不重写 v0.87 已有 tenant_pools DDL, 仅生成新表 DDL
-- 守门 #11 缺标比错标: P0-4 阶段只生成模板, P2 阶段 worker 子代理 + testcontainers 实测

BEGIN;


-- ==========================================
-- ops_metrics_config 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- ops_metrics_config RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE ops_metrics_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE ops_metrics_config FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- ops_metrics_config 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS ops_metrics_config_select ON ops_metrics_config;
CREATE POLICY ops_metrics_config_select ON ops_metrics_config
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS ops_metrics_config_insert ON ops_metrics_config;
CREATE POLICY ops_metrics_config_insert ON ops_metrics_config
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS ops_metrics_config_update ON ops_metrics_config;
CREATE POLICY ops_metrics_config_update ON ops_metrics_config
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS ops_metrics_config_delete ON ops_metrics_config;
CREATE POLICY ops_metrics_config_delete ON ops_metrics_config
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ops_metrics_config schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- ops_metrics_config platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS ops_metrics_config_platform_admin ON ops_metrics_config;
CREATE POLICY ops_metrics_config_platform_admin ON ops_metrics_config
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- ops_cluster_action_log 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- ops_cluster_action_log RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE ops_cluster_action_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE ops_cluster_action_log FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- ops_cluster_action_log 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS ops_cluster_action_log_select ON ops_cluster_action_log;
CREATE POLICY ops_cluster_action_log_select ON ops_cluster_action_log
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS ops_cluster_action_log_insert ON ops_cluster_action_log;
CREATE POLICY ops_cluster_action_log_insert ON ops_cluster_action_log
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS ops_cluster_action_log_update ON ops_cluster_action_log;
CREATE POLICY ops_cluster_action_log_update ON ops_cluster_action_log
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS ops_cluster_action_log_delete ON ops_cluster_action_log;
CREATE POLICY ops_cluster_action_log_delete ON ops_cluster_action_log
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ops_cluster_action_log schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- ops_cluster_action_log platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS ops_cluster_action_log_platform_admin ON ops_cluster_action_log;
CREATE POLICY ops_cluster_action_log_platform_admin ON ops_cluster_action_log
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- ops_helm_release_state 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- ops_helm_release_state RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE ops_helm_release_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE ops_helm_release_state FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- ops_helm_release_state 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS ops_helm_release_state_select ON ops_helm_release_state;
CREATE POLICY ops_helm_release_state_select ON ops_helm_release_state
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS ops_helm_release_state_insert ON ops_helm_release_state;
CREATE POLICY ops_helm_release_state_insert ON ops_helm_release_state
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS ops_helm_release_state_update ON ops_helm_release_state;
CREATE POLICY ops_helm_release_state_update ON ops_helm_release_state
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS ops_helm_release_state_delete ON ops_helm_release_state;
CREATE POLICY ops_helm_release_state_delete ON ops_helm_release_state
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ops_helm_release_state schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- ops_helm_release_state platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS ops_helm_release_state_platform_admin ON ops_helm_release_state;
CREATE POLICY ops_helm_release_state_platform_admin ON ops_helm_release_state
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- ops_log_entry 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- ops_log_entry RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE ops_log_entry ENABLE ROW LEVEL SECURITY;
ALTER TABLE ops_log_entry FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- ops_log_entry 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS ops_log_entry_select ON ops_log_entry;
CREATE POLICY ops_log_entry_select ON ops_log_entry
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS ops_log_entry_insert ON ops_log_entry;
CREATE POLICY ops_log_entry_insert ON ops_log_entry
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS ops_log_entry_update ON ops_log_entry;
CREATE POLICY ops_log_entry_update ON ops_log_entry
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS ops_log_entry_delete ON ops_log_entry;
CREATE POLICY ops_log_entry_delete ON ops_log_entry
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ops_log_entry schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- ops_log_entry platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS ops_log_entry_platform_admin ON ops_log_entry;
CREATE POLICY ops_log_entry_platform_admin ON ops_log_entry
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- ops_log_analysis 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- ops_log_analysis RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE ops_log_analysis ENABLE ROW LEVEL SECURITY;
ALTER TABLE ops_log_analysis FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- ops_log_analysis 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS ops_log_analysis_select ON ops_log_analysis;
CREATE POLICY ops_log_analysis_select ON ops_log_analysis
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS ops_log_analysis_insert ON ops_log_analysis;
CREATE POLICY ops_log_analysis_insert ON ops_log_analysis
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS ops_log_analysis_update ON ops_log_analysis;
CREATE POLICY ops_log_analysis_update ON ops_log_analysis
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS ops_log_analysis_delete ON ops_log_analysis;
CREATE POLICY ops_log_analysis_delete ON ops_log_analysis
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ops_log_analysis schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- ops_log_analysis platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS ops_log_analysis_platform_admin ON ops_log_analysis;
CREATE POLICY ops_log_analysis_platform_admin ON ops_log_analysis
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- ops_log_query_log 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- ops_log_query_log RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE ops_log_query_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE ops_log_query_log FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- ops_log_query_log 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS ops_log_query_log_select ON ops_log_query_log;
CREATE POLICY ops_log_query_log_select ON ops_log_query_log
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS ops_log_query_log_insert ON ops_log_query_log;
CREATE POLICY ops_log_query_log_insert ON ops_log_query_log
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS ops_log_query_log_update ON ops_log_query_log;
CREATE POLICY ops_log_query_log_update ON ops_log_query_log
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS ops_log_query_log_delete ON ops_log_query_log;
CREATE POLICY ops_log_query_log_delete ON ops_log_query_log
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ops_log_query_log schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- ops_log_query_log platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS ops_log_query_log_platform_admin ON ops_log_query_log;
CREATE POLICY ops_log_query_log_platform_admin ON ops_log_query_log
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- oauth_clients 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- oauth_clients RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE oauth_clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE oauth_clients FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- oauth_clients 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS oauth_clients_select ON oauth_clients;
CREATE POLICY oauth_clients_select ON oauth_clients
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS oauth_clients_insert ON oauth_clients;
CREATE POLICY oauth_clients_insert ON oauth_clients
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS oauth_clients_update ON oauth_clients;
CREATE POLICY oauth_clients_update ON oauth_clients
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS oauth_clients_delete ON oauth_clients;
CREATE POLICY oauth_clients_delete ON oauth_clients
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- oauth_clients schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- oauth_clients platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS oauth_clients_platform_admin ON oauth_clients;
CREATE POLICY oauth_clients_platform_admin ON oauth_clients
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- oauth_authorization_codes 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- oauth_authorization_codes RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE oauth_authorization_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE oauth_authorization_codes FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- oauth_authorization_codes 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS oauth_authorization_codes_select ON oauth_authorization_codes;
CREATE POLICY oauth_authorization_codes_select ON oauth_authorization_codes
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS oauth_authorization_codes_insert ON oauth_authorization_codes;
CREATE POLICY oauth_authorization_codes_insert ON oauth_authorization_codes
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS oauth_authorization_codes_update ON oauth_authorization_codes;
CREATE POLICY oauth_authorization_codes_update ON oauth_authorization_codes
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS oauth_authorization_codes_delete ON oauth_authorization_codes;
CREATE POLICY oauth_authorization_codes_delete ON oauth_authorization_codes
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- oauth_authorization_codes schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- oauth_authorization_codes platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS oauth_authorization_codes_platform_admin ON oauth_authorization_codes;
CREATE POLICY oauth_authorization_codes_platform_admin ON oauth_authorization_codes
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- oauth_access_tokens 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- oauth_access_tokens RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE oauth_access_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE oauth_access_tokens FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- oauth_access_tokens 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS oauth_access_tokens_select ON oauth_access_tokens;
CREATE POLICY oauth_access_tokens_select ON oauth_access_tokens
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS oauth_access_tokens_insert ON oauth_access_tokens;
CREATE POLICY oauth_access_tokens_insert ON oauth_access_tokens
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS oauth_access_tokens_update ON oauth_access_tokens;
CREATE POLICY oauth_access_tokens_update ON oauth_access_tokens
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS oauth_access_tokens_delete ON oauth_access_tokens;
CREATE POLICY oauth_access_tokens_delete ON oauth_access_tokens
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- oauth_access_tokens schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- oauth_access_tokens platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS oauth_access_tokens_platform_admin ON oauth_access_tokens;
CREATE POLICY oauth_access_tokens_platform_admin ON oauth_access_tokens
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- oauth_refresh_tokens 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- oauth_refresh_tokens RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE oauth_refresh_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE oauth_refresh_tokens FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- oauth_refresh_tokens 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS oauth_refresh_tokens_select ON oauth_refresh_tokens;
CREATE POLICY oauth_refresh_tokens_select ON oauth_refresh_tokens
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS oauth_refresh_tokens_insert ON oauth_refresh_tokens;
CREATE POLICY oauth_refresh_tokens_insert ON oauth_refresh_tokens
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS oauth_refresh_tokens_update ON oauth_refresh_tokens;
CREATE POLICY oauth_refresh_tokens_update ON oauth_refresh_tokens
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS oauth_refresh_tokens_delete ON oauth_refresh_tokens;
CREATE POLICY oauth_refresh_tokens_delete ON oauth_refresh_tokens
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- oauth_refresh_tokens schema_isolation 跳过 (表无 schema_name 列, per v0.93 缺口 (d) 修)
-- P2 阶段扩展多 schema (per §13.5) 时 ALTER TABLE ADD COLUMN schema_name + 加进 TABLES_WITH_SCHEMA_NAME 白名单

-- oauth_refresh_tokens platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS oauth_refresh_tokens_platform_admin ON oauth_refresh_tokens;
CREATE POLICY oauth_refresh_tokens_platform_admin ON oauth_refresh_tokens
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);


-- ==========================================
-- tenant_pools 7 类 RLS policy (per v0.91 命名)
-- ==========================================

-- tenant_pools RLS (per v0.91 §8 命名, 7 类 policy 模板)
ALTER TABLE tenant_pools ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_pools FORCE ROW LEVEL SECURITY; -- superuser 也走 RLS (per ADR-0043)

-- tenant_pools 4 类CRUD policy (per v0.91 §8.3 映射表 1-4, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS tenant_pools_select ON tenant_pools;
CREATE POLICY tenant_pools_select ON tenant_pools
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS tenant_pools_insert ON tenant_pools;
CREATE POLICY tenant_pools_insert ON tenant_pools
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS tenant_pools_update ON tenant_pools;
CREATE POLICY tenant_pools_update ON tenant_pools
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS tenant_pools_delete ON tenant_pools;
CREATE POLICY tenant_pools_delete ON tenant_pools
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- tenant_pools schema isolation (per v0.91 §8.3 映射表 5, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS tenant_pools_schema_isolation ON tenant_pools;
CREATE POLICY tenant_pools_schema_isolation ON tenant_pools
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

-- tenant_pools platform admin override (per v0.91 §8.3 映射表 6 + v0.88 BYPASSRLS, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS tenant_pools_platform_admin ON tenant_pools;
CREATE POLICY tenant_pools_platform_admin ON tenant_pools
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

-- tenant_pools health_status 派生 visibility (per v0.91 §8.3 映射表 7, 5 status OR 合并, v0.97 加 DROP IF EXISTS 兼容 PG 9.5+)
DROP POLICY IF EXISTS tenant_pools_health_visibility ON tenant_pools;
CREATE POLICY tenant_pools_health_visibility ON tenant_pools
    FOR SELECT
    USING (
        (health_status = 'Healthy' AND current_setting('app.can_see_healthy', true) = 'true')
        OR (health_status = 'Degraded' AND current_setting('app.can_see_degraded', true) = 'true')
        OR (health_status = 'Down' AND current_setting('app.can_see_down', true) = 'true')
        OR (health_status = 'Deleted' AND current_setting('app.can_see_deleted', true) = 'true')
        OR (health_status = 'NotChecked' AND current_setting('app.can_see_notchecked', true) = 'true')
        OR current_setting('app.is_admin', true) = 'true'
    );


COMMIT;
