-- 2026-09-10-p3d6-13-tables.sql (auto-generated by scripts/sql/p3d6_13_tables_gen.py)
-- v1.00 P0-4 Stage 4.4 = P3-D.6 14+15 张表真实 schema 自动 fill 脚本 (per v0.99 §3 已知缺口 (d))
-- (per v0.94 §3 已知缺口 (a) 'P0-4 阶段 26 张占位表, P2 阶段 worker 子代理 fill 真实 schema' 跨 session 续做)
--
-- 守门 #13 a 100% RLS: ENABLE + FORCE + 7 类 policy (走 v0.92 rls_7_policy_gen.py 模板)
-- 守门 #13 b 物理删除禁止: 4 类 CRUD delete 仅 platform_admin
-- 守门 #13 c M SCD Type 2: pgpool_version 字段 + 视图
-- 守门 #13 d T 100% audit: audit trigger 跨 RLS (per ADR-0043 WORM)
-- 守门 #19 v19 复用 v0.99 schema 模板 + v0.97 DROP IF EXISTS idempotent + v0.92 7 类 RLS policy
-- 守门 #11 缺标比错标: P0-4 阶段 13 张表 column name 占位, P2 阶段 worker 子代理 fill 真实

BEGIN;

-- 2026-09-10-p3d6-schema-template.sql
-- v0.99 P0-4 Stage 4.3 模板 (P2 阶段 fill)
-- 表: agent_sessions (per DD-CANVAS-AGENT-001 §4.14.1)
-- v0.99 P0-4 Stage 4.3 = P3-D.6 14+15 张表真实 schema 模板
-- (per v0.94 §3 已知缺口 (a) 'P0-4 阶段 26 张占位表, P2 阶段 worker 子代理 + P3-D.6 阶段 2 任务 2.x 实跑时 ALTER TABLE CREATE TABLE 真实 schema 替换占位' 跨 session 续做)
--
-- 本模板 1 张占位表 `agent_sessions` 完整 schema (含 CREATE TABLE IF NOT EXISTS + 7 类 RLS policy + IF NOT EXISTS idempotent + DROP IF EXISTS 兼容 PG 9.5+),
-- P2 阶段 worker 子代理 复制模板改 table name + column name 走 14 张表.
--
-- 守门 #13 a 100% RLS: ENABLE + FORCE + 7 类 policy
-- 守门 #13 b 物理删除禁止: 4 类 CRUD delete 仅 platform_admin
-- 守门 #13 c M SCD Type 2: pgpool_version 字段
-- 守门 #13 d T 100% audit: audit trigger 跨 RLS (per ADR-0043 WORM)
-- 守门 #1 禁回溯叙事: 不重写 v0.82 tenant_pools DDL, 仅新 commit + 模板声明
-- 守门 #11 缺标比错标: P0-4 阶段 1 张占位表完整 schema, P2 阶段 worker 子代理 fill 13 张

BEGIN;

-- ==========================================
-- 1. agent_sessions 表 (per DD-CANVAS-AGENT-001 §4.14.1 + 守门 #13 c SCD Type 2)
-- 模板: P2 阶段 worker 子代理 改 table name + column name 走 14 张
-- ==========================================
CREATE TABLE IF NOT EXISTS agent_sessions (
    -- 业务字段 (per DD §4.14.1)
    id              UUID NOT NULL,
    tenant_id       UUID NOT NULL,                        -- 守门 #13 a 100% RLS 13 类必带
    agent_id        UUID NOT NULL,                        -- 关联 agent 域 (per DD-CANVAS-AGENT-001)
    session_token   TEXT NOT NULL,                        -- 会话 token (per OAuth2 server v0.43 模式)
    status          TEXT NOT NULL DEFAULT 'Active',       -- Active/Expired/Revoked (per §5 状态机)
    expires_at      TIMESTAMPTZ NOT NULL,                 -- 过期时间 (per OAuth2 短期 token)
    schema_name     TEXT NOT NULL DEFAULT 'public',       -- 守门 #13 a + §13.5 多 schema
    -- 审计字段 (守门 #13 d T 100% audit + ADR-0043 WORM append-only)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID NOT NULL,
    pgpool_version  BIGINT NOT NULL DEFAULT 1,            -- 守门 #13 c SCD Type 2
    -- 显式主键
    PRIMARY KEY (id, pgpool_version),
    UNIQUE (tenant_id, pgpool_version)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_agent_sessions_tenant_id
    ON agent_sessions (tenant_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_agent_id
    ON agent_sessions (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_expires_at
    ON agent_sessions (expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_status
    ON agent_sessions (status)
    WHERE status != 'Active';

-- 当前 SCD Type 2 "有效" version 视图
CREATE OR REPLACE VIEW v_agent_sessions_current AS
SELECT DISTINCT ON (tenant_id, agent_id) *
FROM agent_sessions
ORDER BY tenant_id, agent_id, pgpool_version DESC;

-- AuditEvent WORM 触发器 (守门 #13 d 100% audit + ADR-0043 WORM)
CREATE OR REPLACE FUNCTION agent_sessions_audit_trigger() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO audit_audit_event (
        id, tenant_id, source_kind, source_id, action, row_data, actor_id, created_at
    ) VALUES (
        gen_random_uuid(),
        COALESCE(NEW.tenant_id, OLD.tenant_id),
        'AgentSession',
        COALESCE(NEW.id, OLD.id),
        TG_OP,
        to_jsonb(COALESCE(NEW, OLD)),
        COALESCE(NEW.updated_by, OLD.updated_by, NEW.created_by, OLD.created_by),
        NOW()
    );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_agent_sessions_audit
    AFTER INSERT OR UPDATE OR DELETE ON agent_sessions
    FOR EACH ROW
    EXECUTE FUNCTION agent_sessions_audit_trigger();

-- ==========================================
-- 2. RLS 7 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 模板: 复制到 14 张表 + 改 table name
-- ==========================================
ALTER TABLE agent_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_sessions FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS agent_sessions_select ON agent_sessions;
CREATE POLICY agent_sessions_select ON agent_sessions
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_insert ON agent_sessions;
CREATE POLICY agent_sessions_insert ON agent_sessions
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_update ON agent_sessions;
CREATE POLICY agent_sessions_update ON agent_sessions
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_delete ON agent_sessions;
CREATE POLICY agent_sessions_delete ON agent_sessions
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ==========================================
-- 3. RLS policy 占位: 跨 schema_name 隔离 + platform_admin override
-- ==========================================
DROP POLICY IF EXISTS agent_sessions_schema_isolation ON agent_sessions;
CREATE POLICY agent_sessions_schema_isolation ON agent_sessions
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_platform_admin ON agent_sessions;
CREATE POLICY agent_sessions_platform_admin ON agent_sessions
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;
-- 2026-09-10-p3d6-schema-template.sql
-- v0.99 P0-4 Stage 4.3 模板 (P2 阶段 fill)
-- 表: agent_policies (per DD-CANVAS-AGENT-001 §3.2)
-- v0.99 P0-4 Stage 4.3 = P3-D.6 14+15 张表真实 schema 模板
-- (per v0.94 §3 已知缺口 (a) 'P0-4 阶段 26 张占位表, P2 阶段 worker 子代理 + P3-D.6 阶段 2 任务 2.x 实跑时 ALTER TABLE CREATE TABLE 真实 schema 替换占位' 跨 session 续做)
--
-- 本模板 1 张占位表 `agent_policies` 完整 schema (含 CREATE TABLE IF NOT EXISTS + 7 类 RLS policy + IF NOT EXISTS idempotent + DROP IF EXISTS 兼容 PG 9.5+),
-- P2 阶段 worker 子代理 复制模板改 table name + column name 走 14 张表.
--
-- 守门 #13 a 100% RLS: ENABLE + FORCE + 7 类 policy
-- 守门 #13 b 物理删除禁止: 4 类 CRUD delete 仅 platform_admin
-- 守门 #13 c M SCD Type 2: pgpool_version 字段
-- 守门 #13 d T 100% audit: audit trigger 跨 RLS (per ADR-0043 WORM)
-- 守门 #1 禁回溯叙事: 不重写 v0.82 tenant_pools DDL, 仅新 commit + 模板声明
-- 守门 #11 缺标比错标: P0-4 阶段 1 张占位表完整 schema, P2 阶段 worker 子代理 fill 13 张

BEGIN;

-- ==========================================
-- 1. agent_policies 表 (per DD-CANVAS-AGENT-001 §4.14.1 + 守门 #13 c SCD Type 2)
-- 模板: P2 阶段 worker 子代理 改 table name + column name 走 14 张
-- ==========================================
CREATE TABLE IF NOT EXISTS agent_policies (
    -- 业务字段 (per DD §4.14.1)
    id              UUID NOT NULL,
    tenant_id       UUID NOT NULL,                        -- 守门 #13 a 100% RLS 13 类必带
    agent_id        UUID NOT NULL,                        -- 关联 agent 域 (per DD-CANVAS-AGENT-001)
    session_token   TEXT NOT NULL,                        -- 会话 token (per OAuth2 server v0.43 模式)
    status          TEXT NOT NULL DEFAULT 'Active',       -- Active/Expired/Revoked (per §5 状态机)
    expires_at      TIMESTAMPTZ NOT NULL,                 -- 过期时间 (per OAuth2 短期 token)
    schema_name     TEXT NOT NULL DEFAULT 'public',       -- 守门 #13 a + §13.5 多 schema
    -- 审计字段 (守门 #13 d T 100% audit + ADR-0043 WORM append-only)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID NOT NULL,
    pgpool_version  BIGINT NOT NULL DEFAULT 1,            -- 守门 #13 c SCD Type 2
    -- 显式主键
    PRIMARY KEY (id, pgpool_version),
    UNIQUE (tenant_id, pgpool_version)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_agent_sessions_tenant_id
    ON agent_policies (tenant_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_agent_id
    ON agent_policies (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_expires_at
    ON agent_policies (expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_status
    ON agent_policies (status)
    WHERE status != 'Active';

-- 当前 SCD Type 2 "有效" version 视图
CREATE OR REPLACE VIEW v_agent_sessions_current AS
SELECT DISTINCT ON (tenant_id, agent_id) *
FROM agent_policies
ORDER BY tenant_id, agent_id, pgpool_version DESC;

-- AuditEvent WORM 触发器 (守门 #13 d 100% audit + ADR-0043 WORM)
CREATE OR REPLACE FUNCTION agent_sessions_audit_trigger() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO audit_audit_event (
        id, tenant_id, source_kind, source_id, action, row_data, actor_id, created_at
    ) VALUES (
        gen_random_uuid(),
        COALESCE(NEW.tenant_id, OLD.tenant_id),
        'AgentSession',
        COALESCE(NEW.id, OLD.id),
        TG_OP,
        to_jsonb(COALESCE(NEW, OLD)),
        COALESCE(NEW.updated_by, OLD.updated_by, NEW.created_by, OLD.created_by),
        NOW()
    );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_agent_sessions_audit
    AFTER INSERT OR UPDATE OR DELETE ON agent_policies
    FOR EACH ROW
    EXECUTE FUNCTION agent_sessions_audit_trigger();

-- ==========================================
-- 2. RLS 7 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 模板: 复制到 14 张表 + 改 table name
-- ==========================================
ALTER TABLE agent_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_policies FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS agent_sessions_select ON agent_policies;
CREATE POLICY agent_sessions_select ON agent_policies
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_insert ON agent_policies;
CREATE POLICY agent_sessions_insert ON agent_policies
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_update ON agent_policies;
CREATE POLICY agent_sessions_update ON agent_policies
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_delete ON agent_policies;
CREATE POLICY agent_sessions_delete ON agent_policies
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ==========================================
-- 3. RLS policy 占位: 跨 schema_name 隔离 + platform_admin override
-- ==========================================
DROP POLICY IF EXISTS agent_sessions_schema_isolation ON agent_policies;
CREATE POLICY agent_sessions_schema_isolation ON agent_policies
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_platform_admin ON agent_policies;
CREATE POLICY agent_sessions_platform_admin ON agent_policies
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;
-- 2026-09-10-p3d6-schema-template.sql
-- v0.99 P0-4 Stage 4.3 模板 (P2 阶段 fill)
-- 表: agent_actions (per DD-CANVAS-AGENT-001 §3.3 (AuditEvent WORM 跨 RLS))
-- v0.99 P0-4 Stage 4.3 = P3-D.6 14+15 张表真实 schema 模板
-- (per v0.94 §3 已知缺口 (a) 'P0-4 阶段 26 张占位表, P2 阶段 worker 子代理 + P3-D.6 阶段 2 任务 2.x 实跑时 ALTER TABLE CREATE TABLE 真实 schema 替换占位' 跨 session 续做)
--
-- 本模板 1 张占位表 `agent_actions` 完整 schema (含 CREATE TABLE IF NOT EXISTS + 7 类 RLS policy + IF NOT EXISTS idempotent + DROP IF EXISTS 兼容 PG 9.5+),
-- P2 阶段 worker 子代理 复制模板改 table name + column name 走 14 张表.
--
-- 守门 #13 a 100% RLS: ENABLE + FORCE + 7 类 policy
-- 守门 #13 b 物理删除禁止: 4 类 CRUD delete 仅 platform_admin
-- 守门 #13 c M SCD Type 2: pgpool_version 字段
-- 守门 #13 d T 100% audit: audit trigger 跨 RLS (per ADR-0043 WORM)
-- 守门 #1 禁回溯叙事: 不重写 v0.82 tenant_pools DDL, 仅新 commit + 模板声明
-- 守门 #11 缺标比错标: P0-4 阶段 1 张占位表完整 schema, P2 阶段 worker 子代理 fill 13 张

BEGIN;

-- ==========================================
-- 1. agent_actions 表 (per DD-CANVAS-AGENT-001 §4.14.1 + 守门 #13 c SCD Type 2)
-- 模板: P2 阶段 worker 子代理 改 table name + column name 走 14 张
-- ==========================================
CREATE TABLE IF NOT EXISTS agent_actions (
    -- 业务字段 (per DD §4.14.1)
    id              UUID NOT NULL,
    tenant_id       UUID NOT NULL,                        -- 守门 #13 a 100% RLS 13 类必带
    agent_id        UUID NOT NULL,                        -- 关联 agent 域 (per DD-CANVAS-AGENT-001)
    session_token   TEXT NOT NULL,                        -- 会话 token (per OAuth2 server v0.43 模式)
    status          TEXT NOT NULL DEFAULT 'Active',       -- Active/Expired/Revoked (per §5 状态机)
    expires_at      TIMESTAMPTZ NOT NULL,                 -- 过期时间 (per OAuth2 短期 token)
    schema_name     TEXT NOT NULL DEFAULT 'public',       -- 守门 #13 a + §13.5 多 schema
    -- 审计字段 (守门 #13 d T 100% audit + ADR-0043 WORM append-only)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID NOT NULL,
    pgpool_version  BIGINT NOT NULL DEFAULT 1,            -- 守门 #13 c SCD Type 2
    -- 显式主键
    PRIMARY KEY (id, pgpool_version),
    UNIQUE (tenant_id, pgpool_version)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_agent_sessions_tenant_id
    ON agent_actions (tenant_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_agent_id
    ON agent_actions (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_expires_at
    ON agent_actions (expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_status
    ON agent_actions (status)
    WHERE status != 'Active';

-- 当前 SCD Type 2 "有效" version 视图
CREATE OR REPLACE VIEW v_agent_sessions_current AS
SELECT DISTINCT ON (tenant_id, agent_id) *
FROM agent_actions
ORDER BY tenant_id, agent_id, pgpool_version DESC;

-- AuditEvent WORM 触发器 (守门 #13 d 100% audit + ADR-0043 WORM)
CREATE OR REPLACE FUNCTION agent_sessions_audit_trigger() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO audit_audit_event (
        id, tenant_id, source_kind, source_id, action, row_data, actor_id, created_at
    ) VALUES (
        gen_random_uuid(),
        COALESCE(NEW.tenant_id, OLD.tenant_id),
        'AgentSession',
        COALESCE(NEW.id, OLD.id),
        TG_OP,
        to_jsonb(COALESCE(NEW, OLD)),
        COALESCE(NEW.updated_by, OLD.updated_by, NEW.created_by, OLD.created_by),
        NOW()
    );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_agent_sessions_audit
    AFTER INSERT OR UPDATE OR DELETE ON agent_actions
    FOR EACH ROW
    EXECUTE FUNCTION agent_sessions_audit_trigger();

-- ==========================================
-- 2. RLS 7 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 模板: 复制到 14 张表 + 改 table name
-- ==========================================
ALTER TABLE agent_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_actions FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS agent_sessions_select ON agent_actions;
CREATE POLICY agent_sessions_select ON agent_actions
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_insert ON agent_actions;
CREATE POLICY agent_sessions_insert ON agent_actions
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_update ON agent_actions;
CREATE POLICY agent_sessions_update ON agent_actions
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_delete ON agent_actions;
CREATE POLICY agent_sessions_delete ON agent_actions
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ==========================================
-- 3. RLS policy 占位: 跨 schema_name 隔离 + platform_admin override
-- ==========================================
DROP POLICY IF EXISTS agent_sessions_schema_isolation ON agent_actions;
CREATE POLICY agent_sessions_schema_isolation ON agent_actions
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_platform_admin ON agent_actions;
CREATE POLICY agent_sessions_platform_admin ON agent_actions
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;
-- 2026-09-10-p3d6-schema-template.sql
-- v0.99 P0-4 Stage 4.3 模板 (P2 阶段 fill)
-- 表: agent_relationships (per DD-AGENT-RELATIONSHIP-001 §3.1)
-- v0.99 P0-4 Stage 4.3 = P3-D.6 14+15 张表真实 schema 模板
-- (per v0.94 §3 已知缺口 (a) 'P0-4 阶段 26 张占位表, P2 阶段 worker 子代理 + P3-D.6 阶段 2 任务 2.x 实跑时 ALTER TABLE CREATE TABLE 真实 schema 替换占位' 跨 session 续做)
--
-- 本模板 1 张占位表 `agent_relationships` 完整 schema (含 CREATE TABLE IF NOT EXISTS + 7 类 RLS policy + IF NOT EXISTS idempotent + DROP IF EXISTS 兼容 PG 9.5+),
-- P2 阶段 worker 子代理 复制模板改 table name + column name 走 14 张表.
--
-- 守门 #13 a 100% RLS: ENABLE + FORCE + 7 类 policy
-- 守门 #13 b 物理删除禁止: 4 类 CRUD delete 仅 platform_admin
-- 守门 #13 c M SCD Type 2: pgpool_version 字段
-- 守门 #13 d T 100% audit: audit trigger 跨 RLS (per ADR-0043 WORM)
-- 守门 #1 禁回溯叙事: 不重写 v0.82 tenant_pools DDL, 仅新 commit + 模板声明
-- 守门 #11 缺标比错标: P0-4 阶段 1 张占位表完整 schema, P2 阶段 worker 子代理 fill 13 张

BEGIN;

-- ==========================================
-- 1. agent_relationships 表 (per DD-CANVAS-AGENT-001 §4.14.1 + 守门 #13 c SCD Type 2)
-- 模板: P2 阶段 worker 子代理 改 table name + column name 走 14 张
-- ==========================================
CREATE TABLE IF NOT EXISTS agent_relationships (
    -- 业务字段 (per DD §4.14.1)
    id              UUID NOT NULL,
    tenant_id       UUID NOT NULL,                        -- 守门 #13 a 100% RLS 13 类必带
    agent_id        UUID NOT NULL,                        -- 关联 agent 域 (per DD-CANVAS-AGENT-001)
    session_token   TEXT NOT NULL,                        -- 会话 token (per OAuth2 server v0.43 模式)
    status          TEXT NOT NULL DEFAULT 'Active',       -- Active/Expired/Revoked (per §5 状态机)
    expires_at      TIMESTAMPTZ NOT NULL,                 -- 过期时间 (per OAuth2 短期 token)
    schema_name     TEXT NOT NULL DEFAULT 'public',       -- 守门 #13 a + §13.5 多 schema
    -- 审计字段 (守门 #13 d T 100% audit + ADR-0043 WORM append-only)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID NOT NULL,
    pgpool_version  BIGINT NOT NULL DEFAULT 1,            -- 守门 #13 c SCD Type 2
    -- 显式主键
    PRIMARY KEY (id, pgpool_version),
    UNIQUE (tenant_id, pgpool_version)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_agent_sessions_tenant_id
    ON agent_relationships (tenant_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_agent_id
    ON agent_relationships (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_expires_at
    ON agent_relationships (expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_status
    ON agent_relationships (status)
    WHERE status != 'Active';

-- 当前 SCD Type 2 "有效" version 视图
CREATE OR REPLACE VIEW v_agent_sessions_current AS
SELECT DISTINCT ON (tenant_id, agent_id) *
FROM agent_relationships
ORDER BY tenant_id, agent_id, pgpool_version DESC;

-- AuditEvent WORM 触发器 (守门 #13 d 100% audit + ADR-0043 WORM)
CREATE OR REPLACE FUNCTION agent_sessions_audit_trigger() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO audit_audit_event (
        id, tenant_id, source_kind, source_id, action, row_data, actor_id, created_at
    ) VALUES (
        gen_random_uuid(),
        COALESCE(NEW.tenant_id, OLD.tenant_id),
        'AgentSession',
        COALESCE(NEW.id, OLD.id),
        TG_OP,
        to_jsonb(COALESCE(NEW, OLD)),
        COALESCE(NEW.updated_by, OLD.updated_by, NEW.created_by, OLD.created_by),
        NOW()
    );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_agent_sessions_audit
    AFTER INSERT OR UPDATE OR DELETE ON agent_relationships
    FOR EACH ROW
    EXECUTE FUNCTION agent_sessions_audit_trigger();

-- ==========================================
-- 2. RLS 7 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 模板: 复制到 14 张表 + 改 table name
-- ==========================================
ALTER TABLE agent_relationships ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_relationships FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS agent_sessions_select ON agent_relationships;
CREATE POLICY agent_sessions_select ON agent_relationships
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_insert ON agent_relationships;
CREATE POLICY agent_sessions_insert ON agent_relationships
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_update ON agent_relationships;
CREATE POLICY agent_sessions_update ON agent_relationships
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_delete ON agent_relationships;
CREATE POLICY agent_sessions_delete ON agent_relationships
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ==========================================
-- 3. RLS policy 占位: 跨 schema_name 隔离 + platform_admin override
-- ==========================================
DROP POLICY IF EXISTS agent_sessions_schema_isolation ON agent_relationships;
CREATE POLICY agent_sessions_schema_isolation ON agent_relationships
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_platform_admin ON agent_relationships;
CREATE POLICY agent_sessions_platform_admin ON agent_relationships
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;
-- 2026-09-10-p3d6-schema-template.sql
-- v0.99 P0-4 Stage 4.3 模板 (P2 阶段 fill)
-- 表: agent_trust_scores (per ARG.G-4 TrustAuditLog + 4 重审计)
-- v0.99 P0-4 Stage 4.3 = P3-D.6 14+15 张表真实 schema 模板
-- (per v0.94 §3 已知缺口 (a) 'P0-4 阶段 26 张占位表, P2 阶段 worker 子代理 + P3-D.6 阶段 2 任务 2.x 实跑时 ALTER TABLE CREATE TABLE 真实 schema 替换占位' 跨 session 续做)
--
-- 本模板 1 张占位表 `agent_trust_scores` 完整 schema (含 CREATE TABLE IF NOT EXISTS + 7 类 RLS policy + IF NOT EXISTS idempotent + DROP IF EXISTS 兼容 PG 9.5+),
-- P2 阶段 worker 子代理 复制模板改 table name + column name 走 14 张表.
--
-- 守门 #13 a 100% RLS: ENABLE + FORCE + 7 类 policy
-- 守门 #13 b 物理删除禁止: 4 类 CRUD delete 仅 platform_admin
-- 守门 #13 c M SCD Type 2: pgpool_version 字段
-- 守门 #13 d T 100% audit: audit trigger 跨 RLS (per ADR-0043 WORM)
-- 守门 #1 禁回溯叙事: 不重写 v0.82 tenant_pools DDL, 仅新 commit + 模板声明
-- 守门 #11 缺标比错标: P0-4 阶段 1 张占位表完整 schema, P2 阶段 worker 子代理 fill 13 张

BEGIN;

-- ==========================================
-- 1. agent_trust_scores 表 (per DD-CANVAS-AGENT-001 §4.14.1 + 守门 #13 c SCD Type 2)
-- 模板: P2 阶段 worker 子代理 改 table name + column name 走 14 张
-- ==========================================
CREATE TABLE IF NOT EXISTS agent_trust_scores (
    -- 业务字段 (per DD §4.14.1)
    id              UUID NOT NULL,
    tenant_id       UUID NOT NULL,                        -- 守门 #13 a 100% RLS 13 类必带
    agent_id        UUID NOT NULL,                        -- 关联 agent 域 (per DD-CANVAS-AGENT-001)
    session_token   TEXT NOT NULL,                        -- 会话 token (per OAuth2 server v0.43 模式)
    status          TEXT NOT NULL DEFAULT 'Active',       -- Active/Expired/Revoked (per §5 状态机)
    expires_at      TIMESTAMPTZ NOT NULL,                 -- 过期时间 (per OAuth2 短期 token)
    schema_name     TEXT NOT NULL DEFAULT 'public',       -- 守门 #13 a + §13.5 多 schema
    -- 审计字段 (守门 #13 d T 100% audit + ADR-0043 WORM append-only)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID NOT NULL,
    pgpool_version  BIGINT NOT NULL DEFAULT 1,            -- 守门 #13 c SCD Type 2
    -- 显式主键
    PRIMARY KEY (id, pgpool_version),
    UNIQUE (tenant_id, pgpool_version)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_agent_sessions_tenant_id
    ON agent_trust_scores (tenant_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_agent_id
    ON agent_trust_scores (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_expires_at
    ON agent_trust_scores (expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_status
    ON agent_trust_scores (status)
    WHERE status != 'Active';

-- 当前 SCD Type 2 "有效" version 视图
CREATE OR REPLACE VIEW v_agent_sessions_current AS
SELECT DISTINCT ON (tenant_id, agent_id) *
FROM agent_trust_scores
ORDER BY tenant_id, agent_id, pgpool_version DESC;

-- AuditEvent WORM 触发器 (守门 #13 d 100% audit + ADR-0043 WORM)
CREATE OR REPLACE FUNCTION agent_sessions_audit_trigger() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO audit_audit_event (
        id, tenant_id, source_kind, source_id, action, row_data, actor_id, created_at
    ) VALUES (
        gen_random_uuid(),
        COALESCE(NEW.tenant_id, OLD.tenant_id),
        'AgentSession',
        COALESCE(NEW.id, OLD.id),
        TG_OP,
        to_jsonb(COALESCE(NEW, OLD)),
        COALESCE(NEW.updated_by, OLD.updated_by, NEW.created_by, OLD.created_by),
        NOW()
    );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_agent_sessions_audit
    AFTER INSERT OR UPDATE OR DELETE ON agent_trust_scores
    FOR EACH ROW
    EXECUTE FUNCTION agent_sessions_audit_trigger();

-- ==========================================
-- 2. RLS 7 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 模板: 复制到 14 张表 + 改 table name
-- ==========================================
ALTER TABLE agent_trust_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_trust_scores FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS agent_sessions_select ON agent_trust_scores;
CREATE POLICY agent_sessions_select ON agent_trust_scores
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_insert ON agent_trust_scores;
CREATE POLICY agent_sessions_insert ON agent_trust_scores
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_update ON agent_trust_scores;
CREATE POLICY agent_sessions_update ON agent_trust_scores
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_delete ON agent_trust_scores;
CREATE POLICY agent_sessions_delete ON agent_trust_scores
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ==========================================
-- 3. RLS policy 占位: 跨 schema_name 隔离 + platform_admin override
-- ==========================================
DROP POLICY IF EXISTS agent_sessions_schema_isolation ON agent_trust_scores;
CREATE POLICY agent_sessions_schema_isolation ON agent_trust_scores
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_platform_admin ON agent_trust_scores;
CREATE POLICY agent_sessions_platform_admin ON agent_trust_scores
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;
-- 2026-09-10-p3d6-schema-template.sql
-- v0.99 P0-4 Stage 4.3 模板 (P2 阶段 fill)
-- 表: canvas_elements (per C-25 CanvasElementsBackend (DD §3.1, 协调性检查 v0.63 命名修正))
-- v0.99 P0-4 Stage 4.3 = P3-D.6 14+15 张表真实 schema 模板
-- (per v0.94 §3 已知缺口 (a) 'P0-4 阶段 26 张占位表, P2 阶段 worker 子代理 + P3-D.6 阶段 2 任务 2.x 实跑时 ALTER TABLE CREATE TABLE 真实 schema 替换占位' 跨 session 续做)
--
-- 本模板 1 张占位表 `canvas_elements` 完整 schema (含 CREATE TABLE IF NOT EXISTS + 7 类 RLS policy + IF NOT EXISTS idempotent + DROP IF EXISTS 兼容 PG 9.5+),
-- P2 阶段 worker 子代理 复制模板改 table name + column name 走 14 张表.
--
-- 守门 #13 a 100% RLS: ENABLE + FORCE + 7 类 policy
-- 守门 #13 b 物理删除禁止: 4 类 CRUD delete 仅 platform_admin
-- 守门 #13 c M SCD Type 2: pgpool_version 字段
-- 守门 #13 d T 100% audit: audit trigger 跨 RLS (per ADR-0043 WORM)
-- 守门 #1 禁回溯叙事: 不重写 v0.82 tenant_pools DDL, 仅新 commit + 模板声明
-- 守门 #11 缺标比错标: P0-4 阶段 1 张占位表完整 schema, P2 阶段 worker 子代理 fill 13 张

BEGIN;

-- ==========================================
-- 1. canvas_elements 表 (per DD-CANVAS-AGENT-001 §4.14.1 + 守门 #13 c SCD Type 2)
-- 模板: P2 阶段 worker 子代理 改 table name + column name 走 14 张
-- ==========================================
CREATE TABLE IF NOT EXISTS canvas_elements (
    -- 业务字段 (per DD §4.14.1)
    id              UUID NOT NULL,
    tenant_id       UUID NOT NULL,                        -- 守门 #13 a 100% RLS 13 类必带
    agent_id        UUID NOT NULL,                        -- 关联 agent 域 (per DD-CANVAS-AGENT-001)
    session_token   TEXT NOT NULL,                        -- 会话 token (per OAuth2 server v0.43 模式)
    status          TEXT NOT NULL DEFAULT 'Active',       -- Active/Expired/Revoked (per §5 状态机)
    expires_at      TIMESTAMPTZ NOT NULL,                 -- 过期时间 (per OAuth2 短期 token)
    schema_name     TEXT NOT NULL DEFAULT 'public',       -- 守门 #13 a + §13.5 多 schema
    -- 审计字段 (守门 #13 d T 100% audit + ADR-0043 WORM append-only)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID NOT NULL,
    pgpool_version  BIGINT NOT NULL DEFAULT 1,            -- 守门 #13 c SCD Type 2
    -- 显式主键
    PRIMARY KEY (id, pgpool_version),
    UNIQUE (tenant_id, pgpool_version)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_agent_sessions_tenant_id
    ON canvas_elements (tenant_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_agent_id
    ON canvas_elements (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_expires_at
    ON canvas_elements (expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_status
    ON canvas_elements (status)
    WHERE status != 'Active';

-- 当前 SCD Type 2 "有效" version 视图
CREATE OR REPLACE VIEW v_agent_sessions_current AS
SELECT DISTINCT ON (tenant_id, agent_id) *
FROM canvas_elements
ORDER BY tenant_id, agent_id, pgpool_version DESC;

-- AuditEvent WORM 触发器 (守门 #13 d 100% audit + ADR-0043 WORM)
CREATE OR REPLACE FUNCTION agent_sessions_audit_trigger() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO audit_audit_event (
        id, tenant_id, source_kind, source_id, action, row_data, actor_id, created_at
    ) VALUES (
        gen_random_uuid(),
        COALESCE(NEW.tenant_id, OLD.tenant_id),
        'AgentSession',
        COALESCE(NEW.id, OLD.id),
        TG_OP,
        to_jsonb(COALESCE(NEW, OLD)),
        COALESCE(NEW.updated_by, OLD.updated_by, NEW.created_by, OLD.created_by),
        NOW()
    );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_agent_sessions_audit
    AFTER INSERT OR UPDATE OR DELETE ON canvas_elements
    FOR EACH ROW
    EXECUTE FUNCTION agent_sessions_audit_trigger();

-- ==========================================
-- 2. RLS 7 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 模板: 复制到 14 张表 + 改 table name
-- ==========================================
ALTER TABLE canvas_elements ENABLE ROW LEVEL SECURITY;
ALTER TABLE canvas_elements FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS agent_sessions_select ON canvas_elements;
CREATE POLICY agent_sessions_select ON canvas_elements
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_insert ON canvas_elements;
CREATE POLICY agent_sessions_insert ON canvas_elements
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_update ON canvas_elements;
CREATE POLICY agent_sessions_update ON canvas_elements
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_delete ON canvas_elements;
CREATE POLICY agent_sessions_delete ON canvas_elements
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ==========================================
-- 3. RLS policy 占位: 跨 schema_name 隔离 + platform_admin override
-- ==========================================
DROP POLICY IF EXISTS agent_sessions_schema_isolation ON canvas_elements;
CREATE POLICY agent_sessions_schema_isolation ON canvas_elements
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_platform_admin ON canvas_elements;
CREATE POLICY agent_sessions_platform_admin ON canvas_elements
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;
-- 2026-09-10-p3d6-schema-template.sql
-- v0.99 P0-4 Stage 4.3 模板 (P2 阶段 fill)
-- 表: canvas_multi_user_audit (per C-26 CanvasMultiUserAudit (DD §3.2, 守门 #13 d Transaction 100% audit))
-- v0.99 P0-4 Stage 4.3 = P3-D.6 14+15 张表真实 schema 模板
-- (per v0.94 §3 已知缺口 (a) 'P0-4 阶段 26 张占位表, P2 阶段 worker 子代理 + P3-D.6 阶段 2 任务 2.x 实跑时 ALTER TABLE CREATE TABLE 真实 schema 替换占位' 跨 session 续做)
--
-- 本模板 1 张占位表 `canvas_multi_user_audit` 完整 schema (含 CREATE TABLE IF NOT EXISTS + 7 类 RLS policy + IF NOT EXISTS idempotent + DROP IF EXISTS 兼容 PG 9.5+),
-- P2 阶段 worker 子代理 复制模板改 table name + column name 走 14 张表.
--
-- 守门 #13 a 100% RLS: ENABLE + FORCE + 7 类 policy
-- 守门 #13 b 物理删除禁止: 4 类 CRUD delete 仅 platform_admin
-- 守门 #13 c M SCD Type 2: pgpool_version 字段
-- 守门 #13 d T 100% audit: audit trigger 跨 RLS (per ADR-0043 WORM)
-- 守门 #1 禁回溯叙事: 不重写 v0.82 tenant_pools DDL, 仅新 commit + 模板声明
-- 守门 #11 缺标比错标: P0-4 阶段 1 张占位表完整 schema, P2 阶段 worker 子代理 fill 13 张

BEGIN;

-- ==========================================
-- 1. canvas_multi_user_audit 表 (per DD-CANVAS-AGENT-001 §4.14.1 + 守门 #13 c SCD Type 2)
-- 模板: P2 阶段 worker 子代理 改 table name + column name 走 14 张
-- ==========================================
CREATE TABLE IF NOT EXISTS canvas_multi_user_audit (
    -- 业务字段 (per DD §4.14.1)
    id              UUID NOT NULL,
    tenant_id       UUID NOT NULL,                        -- 守门 #13 a 100% RLS 13 类必带
    agent_id        UUID NOT NULL,                        -- 关联 agent 域 (per DD-CANVAS-AGENT-001)
    session_token   TEXT NOT NULL,                        -- 会话 token (per OAuth2 server v0.43 模式)
    status          TEXT NOT NULL DEFAULT 'Active',       -- Active/Expired/Revoked (per §5 状态机)
    expires_at      TIMESTAMPTZ NOT NULL,                 -- 过期时间 (per OAuth2 短期 token)
    schema_name     TEXT NOT NULL DEFAULT 'public',       -- 守门 #13 a + §13.5 多 schema
    -- 审计字段 (守门 #13 d T 100% audit + ADR-0043 WORM append-only)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID NOT NULL,
    pgpool_version  BIGINT NOT NULL DEFAULT 1,            -- 守门 #13 c SCD Type 2
    -- 显式主键
    PRIMARY KEY (id, pgpool_version),
    UNIQUE (tenant_id, pgpool_version)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_agent_sessions_tenant_id
    ON canvas_multi_user_audit (tenant_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_agent_id
    ON canvas_multi_user_audit (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_expires_at
    ON canvas_multi_user_audit (expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_status
    ON canvas_multi_user_audit (status)
    WHERE status != 'Active';

-- 当前 SCD Type 2 "有效" version 视图
CREATE OR REPLACE VIEW v_agent_sessions_current AS
SELECT DISTINCT ON (tenant_id, agent_id) *
FROM canvas_multi_user_audit
ORDER BY tenant_id, agent_id, pgpool_version DESC;

-- AuditEvent WORM 触发器 (守门 #13 d 100% audit + ADR-0043 WORM)
CREATE OR REPLACE FUNCTION agent_sessions_audit_trigger() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO audit_audit_event (
        id, tenant_id, source_kind, source_id, action, row_data, actor_id, created_at
    ) VALUES (
        gen_random_uuid(),
        COALESCE(NEW.tenant_id, OLD.tenant_id),
        'AgentSession',
        COALESCE(NEW.id, OLD.id),
        TG_OP,
        to_jsonb(COALESCE(NEW, OLD)),
        COALESCE(NEW.updated_by, OLD.updated_by, NEW.created_by, OLD.created_by),
        NOW()
    );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_agent_sessions_audit
    AFTER INSERT OR UPDATE OR DELETE ON canvas_multi_user_audit
    FOR EACH ROW
    EXECUTE FUNCTION agent_sessions_audit_trigger();

-- ==========================================
-- 2. RLS 7 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 模板: 复制到 14 张表 + 改 table name
-- ==========================================
ALTER TABLE canvas_multi_user_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE canvas_multi_user_audit FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS agent_sessions_select ON canvas_multi_user_audit;
CREATE POLICY agent_sessions_select ON canvas_multi_user_audit
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_insert ON canvas_multi_user_audit;
CREATE POLICY agent_sessions_insert ON canvas_multi_user_audit
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_update ON canvas_multi_user_audit;
CREATE POLICY agent_sessions_update ON canvas_multi_user_audit
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_delete ON canvas_multi_user_audit;
CREATE POLICY agent_sessions_delete ON canvas_multi_user_audit
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ==========================================
-- 3. RLS policy 占位: 跨 schema_name 隔离 + platform_admin override
-- ==========================================
DROP POLICY IF EXISTS agent_sessions_schema_isolation ON canvas_multi_user_audit;
CREATE POLICY agent_sessions_schema_isolation ON canvas_multi_user_audit
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_platform_admin ON canvas_multi_user_audit;
CREATE POLICY agent_sessions_platform_admin ON canvas_multi_user_audit
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;
-- 2026-09-10-p3d6-schema-template.sql
-- v0.99 P0-4 Stage 4.3 模板 (P2 阶段 fill)
-- 表: canvas_reactions (per G7 reaction 3s TTL (SRS-CANVAS-GAMIFY-001))
-- v0.99 P0-4 Stage 4.3 = P3-D.6 14+15 张表真实 schema 模板
-- (per v0.94 §3 已知缺口 (a) 'P0-4 阶段 26 张占位表, P2 阶段 worker 子代理 + P3-D.6 阶段 2 任务 2.x 实跑时 ALTER TABLE CREATE TABLE 真实 schema 替换占位' 跨 session 续做)
--
-- 本模板 1 张占位表 `canvas_reactions` 完整 schema (含 CREATE TABLE IF NOT EXISTS + 7 类 RLS policy + IF NOT EXISTS idempotent + DROP IF EXISTS 兼容 PG 9.5+),
-- P2 阶段 worker 子代理 复制模板改 table name + column name 走 14 张表.
--
-- 守门 #13 a 100% RLS: ENABLE + FORCE + 7 类 policy
-- 守门 #13 b 物理删除禁止: 4 类 CRUD delete 仅 platform_admin
-- 守门 #13 c M SCD Type 2: pgpool_version 字段
-- 守门 #13 d T 100% audit: audit trigger 跨 RLS (per ADR-0043 WORM)
-- 守门 #1 禁回溯叙事: 不重写 v0.82 tenant_pools DDL, 仅新 commit + 模板声明
-- 守门 #11 缺标比错标: P0-4 阶段 1 张占位表完整 schema, P2 阶段 worker 子代理 fill 13 张

BEGIN;

-- ==========================================
-- 1. canvas_reactions 表 (per DD-CANVAS-AGENT-001 §4.14.1 + 守门 #13 c SCD Type 2)
-- 模板: P2 阶段 worker 子代理 改 table name + column name 走 14 张
-- ==========================================
CREATE TABLE IF NOT EXISTS canvas_reactions (
    -- 业务字段 (per DD §4.14.1)
    id              UUID NOT NULL,
    tenant_id       UUID NOT NULL,                        -- 守门 #13 a 100% RLS 13 类必带
    agent_id        UUID NOT NULL,                        -- 关联 agent 域 (per DD-CANVAS-AGENT-001)
    session_token   TEXT NOT NULL,                        -- 会话 token (per OAuth2 server v0.43 模式)
    status          TEXT NOT NULL DEFAULT 'Active',       -- Active/Expired/Revoked (per §5 状态机)
    expires_at      TIMESTAMPTZ NOT NULL,                 -- 过期时间 (per OAuth2 短期 token)
    schema_name     TEXT NOT NULL DEFAULT 'public',       -- 守门 #13 a + §13.5 多 schema
    -- 审计字段 (守门 #13 d T 100% audit + ADR-0043 WORM append-only)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID NOT NULL,
    pgpool_version  BIGINT NOT NULL DEFAULT 1,            -- 守门 #13 c SCD Type 2
    -- 显式主键
    PRIMARY KEY (id, pgpool_version),
    UNIQUE (tenant_id, pgpool_version)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_agent_sessions_tenant_id
    ON canvas_reactions (tenant_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_agent_id
    ON canvas_reactions (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_expires_at
    ON canvas_reactions (expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_status
    ON canvas_reactions (status)
    WHERE status != 'Active';

-- 当前 SCD Type 2 "有效" version 视图
CREATE OR REPLACE VIEW v_agent_sessions_current AS
SELECT DISTINCT ON (tenant_id, agent_id) *
FROM canvas_reactions
ORDER BY tenant_id, agent_id, pgpool_version DESC;

-- AuditEvent WORM 触发器 (守门 #13 d 100% audit + ADR-0043 WORM)
CREATE OR REPLACE FUNCTION agent_sessions_audit_trigger() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO audit_audit_event (
        id, tenant_id, source_kind, source_id, action, row_data, actor_id, created_at
    ) VALUES (
        gen_random_uuid(),
        COALESCE(NEW.tenant_id, OLD.tenant_id),
        'AgentSession',
        COALESCE(NEW.id, OLD.id),
        TG_OP,
        to_jsonb(COALESCE(NEW, OLD)),
        COALESCE(NEW.updated_by, OLD.updated_by, NEW.created_by, OLD.created_by),
        NOW()
    );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_agent_sessions_audit
    AFTER INSERT OR UPDATE OR DELETE ON canvas_reactions
    FOR EACH ROW
    EXECUTE FUNCTION agent_sessions_audit_trigger();

-- ==========================================
-- 2. RLS 7 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 模板: 复制到 14 张表 + 改 table name
-- ==========================================
ALTER TABLE canvas_reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE canvas_reactions FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS agent_sessions_select ON canvas_reactions;
CREATE POLICY agent_sessions_select ON canvas_reactions
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_insert ON canvas_reactions;
CREATE POLICY agent_sessions_insert ON canvas_reactions
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_update ON canvas_reactions;
CREATE POLICY agent_sessions_update ON canvas_reactions
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_delete ON canvas_reactions;
CREATE POLICY agent_sessions_delete ON canvas_reactions
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ==========================================
-- 3. RLS policy 占位: 跨 schema_name 隔离 + platform_admin override
-- ==========================================
DROP POLICY IF EXISTS agent_sessions_schema_isolation ON canvas_reactions;
CREATE POLICY agent_sessions_schema_isolation ON canvas_reactions
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_platform_admin ON canvas_reactions;
CREATE POLICY agent_sessions_platform_admin ON canvas_reactions
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;
-- 2026-09-10-p3d6-schema-template.sql
-- v0.99 P0-4 Stage 4.3 模板 (P2 阶段 fill)
-- 表: canvas_comments (per A12.4 canvas comments)
-- v0.99 P0-4 Stage 4.3 = P3-D.6 14+15 张表真实 schema 模板
-- (per v0.94 §3 已知缺口 (a) 'P0-4 阶段 26 张占位表, P2 阶段 worker 子代理 + P3-D.6 阶段 2 任务 2.x 实跑时 ALTER TABLE CREATE TABLE 真实 schema 替换占位' 跨 session 续做)
--
-- 本模板 1 张占位表 `canvas_comments` 完整 schema (含 CREATE TABLE IF NOT EXISTS + 7 类 RLS policy + IF NOT EXISTS idempotent + DROP IF EXISTS 兼容 PG 9.5+),
-- P2 阶段 worker 子代理 复制模板改 table name + column name 走 14 张表.
--
-- 守门 #13 a 100% RLS: ENABLE + FORCE + 7 类 policy
-- 守门 #13 b 物理删除禁止: 4 类 CRUD delete 仅 platform_admin
-- 守门 #13 c M SCD Type 2: pgpool_version 字段
-- 守门 #13 d T 100% audit: audit trigger 跨 RLS (per ADR-0043 WORM)
-- 守门 #1 禁回溯叙事: 不重写 v0.82 tenant_pools DDL, 仅新 commit + 模板声明
-- 守门 #11 缺标比错标: P0-4 阶段 1 张占位表完整 schema, P2 阶段 worker 子代理 fill 13 张

BEGIN;

-- ==========================================
-- 1. canvas_comments 表 (per DD-CANVAS-AGENT-001 §4.14.1 + 守门 #13 c SCD Type 2)
-- 模板: P2 阶段 worker 子代理 改 table name + column name 走 14 张
-- ==========================================
CREATE TABLE IF NOT EXISTS canvas_comments (
    -- 业务字段 (per DD §4.14.1)
    id              UUID NOT NULL,
    tenant_id       UUID NOT NULL,                        -- 守门 #13 a 100% RLS 13 类必带
    agent_id        UUID NOT NULL,                        -- 关联 agent 域 (per DD-CANVAS-AGENT-001)
    session_token   TEXT NOT NULL,                        -- 会话 token (per OAuth2 server v0.43 模式)
    status          TEXT NOT NULL DEFAULT 'Active',       -- Active/Expired/Revoked (per §5 状态机)
    expires_at      TIMESTAMPTZ NOT NULL,                 -- 过期时间 (per OAuth2 短期 token)
    schema_name     TEXT NOT NULL DEFAULT 'public',       -- 守门 #13 a + §13.5 多 schema
    -- 审计字段 (守门 #13 d T 100% audit + ADR-0043 WORM append-only)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID NOT NULL,
    pgpool_version  BIGINT NOT NULL DEFAULT 1,            -- 守门 #13 c SCD Type 2
    -- 显式主键
    PRIMARY KEY (id, pgpool_version),
    UNIQUE (tenant_id, pgpool_version)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_agent_sessions_tenant_id
    ON canvas_comments (tenant_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_agent_id
    ON canvas_comments (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_expires_at
    ON canvas_comments (expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_status
    ON canvas_comments (status)
    WHERE status != 'Active';

-- 当前 SCD Type 2 "有效" version 视图
CREATE OR REPLACE VIEW v_agent_sessions_current AS
SELECT DISTINCT ON (tenant_id, agent_id) *
FROM canvas_comments
ORDER BY tenant_id, agent_id, pgpool_version DESC;

-- AuditEvent WORM 触发器 (守门 #13 d 100% audit + ADR-0043 WORM)
CREATE OR REPLACE FUNCTION agent_sessions_audit_trigger() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO audit_audit_event (
        id, tenant_id, source_kind, source_id, action, row_data, actor_id, created_at
    ) VALUES (
        gen_random_uuid(),
        COALESCE(NEW.tenant_id, OLD.tenant_id),
        'AgentSession',
        COALESCE(NEW.id, OLD.id),
        TG_OP,
        to_jsonb(COALESCE(NEW, OLD)),
        COALESCE(NEW.updated_by, OLD.updated_by, NEW.created_by, OLD.created_by),
        NOW()
    );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_agent_sessions_audit
    AFTER INSERT OR UPDATE OR DELETE ON canvas_comments
    FOR EACH ROW
    EXECUTE FUNCTION agent_sessions_audit_trigger();

-- ==========================================
-- 2. RLS 7 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 模板: 复制到 14 张表 + 改 table name
-- ==========================================
ALTER TABLE canvas_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE canvas_comments FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS agent_sessions_select ON canvas_comments;
CREATE POLICY agent_sessions_select ON canvas_comments
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_insert ON canvas_comments;
CREATE POLICY agent_sessions_insert ON canvas_comments
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_update ON canvas_comments;
CREATE POLICY agent_sessions_update ON canvas_comments
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_delete ON canvas_comments;
CREATE POLICY agent_sessions_delete ON canvas_comments
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ==========================================
-- 3. RLS policy 占位: 跨 schema_name 隔离 + platform_admin override
-- ==========================================
DROP POLICY IF EXISTS agent_sessions_schema_isolation ON canvas_comments;
CREATE POLICY agent_sessions_schema_isolation ON canvas_comments
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_platform_admin ON canvas_comments;
CREATE POLICY agent_sessions_platform_admin ON canvas_comments
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;
-- 2026-09-10-p3d6-schema-template.sql
-- v0.99 P0-4 Stage 4.3 模板 (P2 阶段 fill)
-- 表: gamify_avatars (per G1 avatar (SRS-CANVAS-GAMIFY-001))
-- v0.99 P0-4 Stage 4.3 = P3-D.6 14+15 张表真实 schema 模板
-- (per v0.94 §3 已知缺口 (a) 'P0-4 阶段 26 张占位表, P2 阶段 worker 子代理 + P3-D.6 阶段 2 任务 2.x 实跑时 ALTER TABLE CREATE TABLE 真实 schema 替换占位' 跨 session 续做)
--
-- 本模板 1 张占位表 `gamify_avatars` 完整 schema (含 CREATE TABLE IF NOT EXISTS + 7 类 RLS policy + IF NOT EXISTS idempotent + DROP IF EXISTS 兼容 PG 9.5+),
-- P2 阶段 worker 子代理 复制模板改 table name + column name 走 14 张表.
--
-- 守门 #13 a 100% RLS: ENABLE + FORCE + 7 类 policy
-- 守门 #13 b 物理删除禁止: 4 类 CRUD delete 仅 platform_admin
-- 守门 #13 c M SCD Type 2: pgpool_version 字段
-- 守门 #13 d T 100% audit: audit trigger 跨 RLS (per ADR-0043 WORM)
-- 守门 #1 禁回溯叙事: 不重写 v0.82 tenant_pools DDL, 仅新 commit + 模板声明
-- 守门 #11 缺标比错标: P0-4 阶段 1 张占位表完整 schema, P2 阶段 worker 子代理 fill 13 张

BEGIN;

-- ==========================================
-- 1. gamify_avatars 表 (per DD-CANVAS-AGENT-001 §4.14.1 + 守门 #13 c SCD Type 2)
-- 模板: P2 阶段 worker 子代理 改 table name + column name 走 14 张
-- ==========================================
CREATE TABLE IF NOT EXISTS gamify_avatars (
    -- 业务字段 (per DD §4.14.1)
    id              UUID NOT NULL,
    tenant_id       UUID NOT NULL,                        -- 守门 #13 a 100% RLS 13 类必带
    agent_id        UUID NOT NULL,                        -- 关联 agent 域 (per DD-CANVAS-AGENT-001)
    session_token   TEXT NOT NULL,                        -- 会话 token (per OAuth2 server v0.43 模式)
    status          TEXT NOT NULL DEFAULT 'Active',       -- Active/Expired/Revoked (per §5 状态机)
    expires_at      TIMESTAMPTZ NOT NULL,                 -- 过期时间 (per OAuth2 短期 token)
    schema_name     TEXT NOT NULL DEFAULT 'public',       -- 守门 #13 a + §13.5 多 schema
    -- 审计字段 (守门 #13 d T 100% audit + ADR-0043 WORM append-only)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID NOT NULL,
    pgpool_version  BIGINT NOT NULL DEFAULT 1,            -- 守门 #13 c SCD Type 2
    -- 显式主键
    PRIMARY KEY (id, pgpool_version),
    UNIQUE (tenant_id, pgpool_version)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_agent_sessions_tenant_id
    ON gamify_avatars (tenant_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_agent_id
    ON gamify_avatars (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_expires_at
    ON gamify_avatars (expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_status
    ON gamify_avatars (status)
    WHERE status != 'Active';

-- 当前 SCD Type 2 "有效" version 视图
CREATE OR REPLACE VIEW v_agent_sessions_current AS
SELECT DISTINCT ON (tenant_id, agent_id) *
FROM gamify_avatars
ORDER BY tenant_id, agent_id, pgpool_version DESC;

-- AuditEvent WORM 触发器 (守门 #13 d 100% audit + ADR-0043 WORM)
CREATE OR REPLACE FUNCTION agent_sessions_audit_trigger() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO audit_audit_event (
        id, tenant_id, source_kind, source_id, action, row_data, actor_id, created_at
    ) VALUES (
        gen_random_uuid(),
        COALESCE(NEW.tenant_id, OLD.tenant_id),
        'AgentSession',
        COALESCE(NEW.id, OLD.id),
        TG_OP,
        to_jsonb(COALESCE(NEW, OLD)),
        COALESCE(NEW.updated_by, OLD.updated_by, NEW.created_by, OLD.created_by),
        NOW()
    );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_agent_sessions_audit
    AFTER INSERT OR UPDATE OR DELETE ON gamify_avatars
    FOR EACH ROW
    EXECUTE FUNCTION agent_sessions_audit_trigger();

-- ==========================================
-- 2. RLS 7 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 模板: 复制到 14 张表 + 改 table name
-- ==========================================
ALTER TABLE gamify_avatars ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamify_avatars FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS agent_sessions_select ON gamify_avatars;
CREATE POLICY agent_sessions_select ON gamify_avatars
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_insert ON gamify_avatars;
CREATE POLICY agent_sessions_insert ON gamify_avatars
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_update ON gamify_avatars;
CREATE POLICY agent_sessions_update ON gamify_avatars
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_delete ON gamify_avatars;
CREATE POLICY agent_sessions_delete ON gamify_avatars
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ==========================================
-- 3. RLS policy 占位: 跨 schema_name 隔离 + platform_admin override
-- ==========================================
DROP POLICY IF EXISTS agent_sessions_schema_isolation ON gamify_avatars;
CREATE POLICY agent_sessions_schema_isolation ON gamify_avatars
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_platform_admin ON gamify_avatars;
CREATE POLICY agent_sessions_platform_admin ON gamify_avatars
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;
-- 2026-09-10-p3d6-schema-template.sql
-- v0.99 P0-4 Stage 4.3 模板 (P2 阶段 fill)
-- 表: gamify_levels (per G2 level (SRS-CANVAS-GAMIFY-001))
-- v0.99 P0-4 Stage 4.3 = P3-D.6 14+15 张表真实 schema 模板
-- (per v0.94 §3 已知缺口 (a) 'P0-4 阶段 26 张占位表, P2 阶段 worker 子代理 + P3-D.6 阶段 2 任务 2.x 实跑时 ALTER TABLE CREATE TABLE 真实 schema 替换占位' 跨 session 续做)
--
-- 本模板 1 张占位表 `gamify_levels` 完整 schema (含 CREATE TABLE IF NOT EXISTS + 7 类 RLS policy + IF NOT EXISTS idempotent + DROP IF EXISTS 兼容 PG 9.5+),
-- P2 阶段 worker 子代理 复制模板改 table name + column name 走 14 张表.
--
-- 守门 #13 a 100% RLS: ENABLE + FORCE + 7 类 policy
-- 守门 #13 b 物理删除禁止: 4 类 CRUD delete 仅 platform_admin
-- 守门 #13 c M SCD Type 2: pgpool_version 字段
-- 守门 #13 d T 100% audit: audit trigger 跨 RLS (per ADR-0043 WORM)
-- 守门 #1 禁回溯叙事: 不重写 v0.82 tenant_pools DDL, 仅新 commit + 模板声明
-- 守门 #11 缺标比错标: P0-4 阶段 1 张占位表完整 schema, P2 阶段 worker 子代理 fill 13 张

BEGIN;

-- ==========================================
-- 1. gamify_levels 表 (per DD-CANVAS-AGENT-001 §4.14.1 + 守门 #13 c SCD Type 2)
-- 模板: P2 阶段 worker 子代理 改 table name + column name 走 14 张
-- ==========================================
CREATE TABLE IF NOT EXISTS gamify_levels (
    -- 业务字段 (per DD §4.14.1)
    id              UUID NOT NULL,
    tenant_id       UUID NOT NULL,                        -- 守门 #13 a 100% RLS 13 类必带
    agent_id        UUID NOT NULL,                        -- 关联 agent 域 (per DD-CANVAS-AGENT-001)
    session_token   TEXT NOT NULL,                        -- 会话 token (per OAuth2 server v0.43 模式)
    status          TEXT NOT NULL DEFAULT 'Active',       -- Active/Expired/Revoked (per §5 状态机)
    expires_at      TIMESTAMPTZ NOT NULL,                 -- 过期时间 (per OAuth2 短期 token)
    schema_name     TEXT NOT NULL DEFAULT 'public',       -- 守门 #13 a + §13.5 多 schema
    -- 审计字段 (守门 #13 d T 100% audit + ADR-0043 WORM append-only)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID NOT NULL,
    pgpool_version  BIGINT NOT NULL DEFAULT 1,            -- 守门 #13 c SCD Type 2
    -- 显式主键
    PRIMARY KEY (id, pgpool_version),
    UNIQUE (tenant_id, pgpool_version)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_agent_sessions_tenant_id
    ON gamify_levels (tenant_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_agent_id
    ON gamify_levels (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_expires_at
    ON gamify_levels (expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_status
    ON gamify_levels (status)
    WHERE status != 'Active';

-- 当前 SCD Type 2 "有效" version 视图
CREATE OR REPLACE VIEW v_agent_sessions_current AS
SELECT DISTINCT ON (tenant_id, agent_id) *
FROM gamify_levels
ORDER BY tenant_id, agent_id, pgpool_version DESC;

-- AuditEvent WORM 触发器 (守门 #13 d 100% audit + ADR-0043 WORM)
CREATE OR REPLACE FUNCTION agent_sessions_audit_trigger() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO audit_audit_event (
        id, tenant_id, source_kind, source_id, action, row_data, actor_id, created_at
    ) VALUES (
        gen_random_uuid(),
        COALESCE(NEW.tenant_id, OLD.tenant_id),
        'AgentSession',
        COALESCE(NEW.id, OLD.id),
        TG_OP,
        to_jsonb(COALESCE(NEW, OLD)),
        COALESCE(NEW.updated_by, OLD.updated_by, NEW.created_by, OLD.created_by),
        NOW()
    );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_agent_sessions_audit
    AFTER INSERT OR UPDATE OR DELETE ON gamify_levels
    FOR EACH ROW
    EXECUTE FUNCTION agent_sessions_audit_trigger();

-- ==========================================
-- 2. RLS 7 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 模板: 复制到 14 张表 + 改 table name
-- ==========================================
ALTER TABLE gamify_levels ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamify_levels FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS agent_sessions_select ON gamify_levels;
CREATE POLICY agent_sessions_select ON gamify_levels
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_insert ON gamify_levels;
CREATE POLICY agent_sessions_insert ON gamify_levels
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_update ON gamify_levels;
CREATE POLICY agent_sessions_update ON gamify_levels
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_delete ON gamify_levels;
CREATE POLICY agent_sessions_delete ON gamify_levels
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ==========================================
-- 3. RLS policy 占位: 跨 schema_name 隔离 + platform_admin override
-- ==========================================
DROP POLICY IF EXISTS agent_sessions_schema_isolation ON gamify_levels;
CREATE POLICY agent_sessions_schema_isolation ON gamify_levels
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_platform_admin ON gamify_levels;
CREATE POLICY agent_sessions_platform_admin ON gamify_levels
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;
-- 2026-09-10-p3d6-schema-template.sql
-- v0.99 P0-4 Stage 4.3 模板 (P2 阶段 fill)
-- 表: gamify_sticky_notes (per G3 sticky (SRS-CANVAS-GAMIFY-001))
-- v0.99 P0-4 Stage 4.3 = P3-D.6 14+15 张表真实 schema 模板
-- (per v0.94 §3 已知缺口 (a) 'P0-4 阶段 26 张占位表, P2 阶段 worker 子代理 + P3-D.6 阶段 2 任务 2.x 实跑时 ALTER TABLE CREATE TABLE 真实 schema 替换占位' 跨 session 续做)
--
-- 本模板 1 张占位表 `gamify_sticky_notes` 完整 schema (含 CREATE TABLE IF NOT EXISTS + 7 类 RLS policy + IF NOT EXISTS idempotent + DROP IF EXISTS 兼容 PG 9.5+),
-- P2 阶段 worker 子代理 复制模板改 table name + column name 走 14 张表.
--
-- 守门 #13 a 100% RLS: ENABLE + FORCE + 7 类 policy
-- 守门 #13 b 物理删除禁止: 4 类 CRUD delete 仅 platform_admin
-- 守门 #13 c M SCD Type 2: pgpool_version 字段
-- 守门 #13 d T 100% audit: audit trigger 跨 RLS (per ADR-0043 WORM)
-- 守门 #1 禁回溯叙事: 不重写 v0.82 tenant_pools DDL, 仅新 commit + 模板声明
-- 守门 #11 缺标比错标: P0-4 阶段 1 张占位表完整 schema, P2 阶段 worker 子代理 fill 13 张

BEGIN;

-- ==========================================
-- 1. gamify_sticky_notes 表 (per DD-CANVAS-AGENT-001 §4.14.1 + 守门 #13 c SCD Type 2)
-- 模板: P2 阶段 worker 子代理 改 table name + column name 走 14 张
-- ==========================================
CREATE TABLE IF NOT EXISTS gamify_sticky_notes (
    -- 业务字段 (per DD §4.14.1)
    id              UUID NOT NULL,
    tenant_id       UUID NOT NULL,                        -- 守门 #13 a 100% RLS 13 类必带
    agent_id        UUID NOT NULL,                        -- 关联 agent 域 (per DD-CANVAS-AGENT-001)
    session_token   TEXT NOT NULL,                        -- 会话 token (per OAuth2 server v0.43 模式)
    status          TEXT NOT NULL DEFAULT 'Active',       -- Active/Expired/Revoked (per §5 状态机)
    expires_at      TIMESTAMPTZ NOT NULL,                 -- 过期时间 (per OAuth2 短期 token)
    schema_name     TEXT NOT NULL DEFAULT 'public',       -- 守门 #13 a + §13.5 多 schema
    -- 审计字段 (守门 #13 d T 100% audit + ADR-0043 WORM append-only)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID NOT NULL,
    pgpool_version  BIGINT NOT NULL DEFAULT 1,            -- 守门 #13 c SCD Type 2
    -- 显式主键
    PRIMARY KEY (id, pgpool_version),
    UNIQUE (tenant_id, pgpool_version)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_agent_sessions_tenant_id
    ON gamify_sticky_notes (tenant_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_agent_id
    ON gamify_sticky_notes (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_expires_at
    ON gamify_sticky_notes (expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_status
    ON gamify_sticky_notes (status)
    WHERE status != 'Active';

-- 当前 SCD Type 2 "有效" version 视图
CREATE OR REPLACE VIEW v_agent_sessions_current AS
SELECT DISTINCT ON (tenant_id, agent_id) *
FROM gamify_sticky_notes
ORDER BY tenant_id, agent_id, pgpool_version DESC;

-- AuditEvent WORM 触发器 (守门 #13 d 100% audit + ADR-0043 WORM)
CREATE OR REPLACE FUNCTION agent_sessions_audit_trigger() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO audit_audit_event (
        id, tenant_id, source_kind, source_id, action, row_data, actor_id, created_at
    ) VALUES (
        gen_random_uuid(),
        COALESCE(NEW.tenant_id, OLD.tenant_id),
        'AgentSession',
        COALESCE(NEW.id, OLD.id),
        TG_OP,
        to_jsonb(COALESCE(NEW, OLD)),
        COALESCE(NEW.updated_by, OLD.updated_by, NEW.created_by, OLD.created_by),
        NOW()
    );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_agent_sessions_audit
    AFTER INSERT OR UPDATE OR DELETE ON gamify_sticky_notes
    FOR EACH ROW
    EXECUTE FUNCTION agent_sessions_audit_trigger();

-- ==========================================
-- 2. RLS 7 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 模板: 复制到 14 张表 + 改 table name
-- ==========================================
ALTER TABLE gamify_sticky_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamify_sticky_notes FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS agent_sessions_select ON gamify_sticky_notes;
CREATE POLICY agent_sessions_select ON gamify_sticky_notes
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_insert ON gamify_sticky_notes;
CREATE POLICY agent_sessions_insert ON gamify_sticky_notes
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_update ON gamify_sticky_notes;
CREATE POLICY agent_sessions_update ON gamify_sticky_notes
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_delete ON gamify_sticky_notes;
CREATE POLICY agent_sessions_delete ON gamify_sticky_notes
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ==========================================
-- 3. RLS policy 占位: 跨 schema_name 隔离 + platform_admin override
-- ==========================================
DROP POLICY IF EXISTS agent_sessions_schema_isolation ON gamify_sticky_notes;
CREATE POLICY agent_sessions_schema_isolation ON gamify_sticky_notes
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_platform_admin ON gamify_sticky_notes;
CREATE POLICY agent_sessions_platform_admin ON gamify_sticky_notes
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;
-- 2026-09-10-p3d6-schema-template.sql
-- v0.99 P0-4 Stage 4.3 模板 (P2 阶段 fill)
-- 表: gamify_confetti (per G4 confetti (SRS-CANVAS-GAMIFY-001))
-- v0.99 P0-4 Stage 4.3 = P3-D.6 14+15 张表真实 schema 模板
-- (per v0.94 §3 已知缺口 (a) 'P0-4 阶段 26 张占位表, P2 阶段 worker 子代理 + P3-D.6 阶段 2 任务 2.x 实跑时 ALTER TABLE CREATE TABLE 真实 schema 替换占位' 跨 session 续做)
--
-- 本模板 1 张占位表 `gamify_confetti` 完整 schema (含 CREATE TABLE IF NOT EXISTS + 7 类 RLS policy + IF NOT EXISTS idempotent + DROP IF EXISTS 兼容 PG 9.5+),
-- P2 阶段 worker 子代理 复制模板改 table name + column name 走 14 张表.
--
-- 守门 #13 a 100% RLS: ENABLE + FORCE + 7 类 policy
-- 守门 #13 b 物理删除禁止: 4 类 CRUD delete 仅 platform_admin
-- 守门 #13 c M SCD Type 2: pgpool_version 字段
-- 守门 #13 d T 100% audit: audit trigger 跨 RLS (per ADR-0043 WORM)
-- 守门 #1 禁回溯叙事: 不重写 v0.82 tenant_pools DDL, 仅新 commit + 模板声明
-- 守门 #11 缺标比错标: P0-4 阶段 1 张占位表完整 schema, P2 阶段 worker 子代理 fill 13 张

BEGIN;

-- ==========================================
-- 1. gamify_confetti 表 (per DD-CANVAS-AGENT-001 §4.14.1 + 守门 #13 c SCD Type 2)
-- 模板: P2 阶段 worker 子代理 改 table name + column name 走 14 张
-- ==========================================
CREATE TABLE IF NOT EXISTS gamify_confetti (
    -- 业务字段 (per DD §4.14.1)
    id              UUID NOT NULL,
    tenant_id       UUID NOT NULL,                        -- 守门 #13 a 100% RLS 13 类必带
    agent_id        UUID NOT NULL,                        -- 关联 agent 域 (per DD-CANVAS-AGENT-001)
    session_token   TEXT NOT NULL,                        -- 会话 token (per OAuth2 server v0.43 模式)
    status          TEXT NOT NULL DEFAULT 'Active',       -- Active/Expired/Revoked (per §5 状态机)
    expires_at      TIMESTAMPTZ NOT NULL,                 -- 过期时间 (per OAuth2 短期 token)
    schema_name     TEXT NOT NULL DEFAULT 'public',       -- 守门 #13 a + §13.5 多 schema
    -- 审计字段 (守门 #13 d T 100% audit + ADR-0043 WORM append-only)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID NOT NULL,
    pgpool_version  BIGINT NOT NULL DEFAULT 1,            -- 守门 #13 c SCD Type 2
    -- 显式主键
    PRIMARY KEY (id, pgpool_version),
    UNIQUE (tenant_id, pgpool_version)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_agent_sessions_tenant_id
    ON gamify_confetti (tenant_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_agent_id
    ON gamify_confetti (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_expires_at
    ON gamify_confetti (expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_status
    ON gamify_confetti (status)
    WHERE status != 'Active';

-- 当前 SCD Type 2 "有效" version 视图
CREATE OR REPLACE VIEW v_agent_sessions_current AS
SELECT DISTINCT ON (tenant_id, agent_id) *
FROM gamify_confetti
ORDER BY tenant_id, agent_id, pgpool_version DESC;

-- AuditEvent WORM 触发器 (守门 #13 d 100% audit + ADR-0043 WORM)
CREATE OR REPLACE FUNCTION agent_sessions_audit_trigger() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO audit_audit_event (
        id, tenant_id, source_kind, source_id, action, row_data, actor_id, created_at
    ) VALUES (
        gen_random_uuid(),
        COALESCE(NEW.tenant_id, OLD.tenant_id),
        'AgentSession',
        COALESCE(NEW.id, OLD.id),
        TG_OP,
        to_jsonb(COALESCE(NEW, OLD)),
        COALESCE(NEW.updated_by, OLD.updated_by, NEW.created_by, OLD.created_by),
        NOW()
    );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_agent_sessions_audit
    AFTER INSERT OR UPDATE OR DELETE ON gamify_confetti
    FOR EACH ROW
    EXECUTE FUNCTION agent_sessions_audit_trigger();

-- ==========================================
-- 2. RLS 7 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 模板: 复制到 14 张表 + 改 table name
-- ==========================================
ALTER TABLE gamify_confetti ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamify_confetti FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS agent_sessions_select ON gamify_confetti;
CREATE POLICY agent_sessions_select ON gamify_confetti
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_insert ON gamify_confetti;
CREATE POLICY agent_sessions_insert ON gamify_confetti
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_update ON gamify_confetti;
CREATE POLICY agent_sessions_update ON gamify_confetti
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_delete ON gamify_confetti;
CREATE POLICY agent_sessions_delete ON gamify_confetti
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ==========================================
-- 3. RLS policy 占位: 跨 schema_name 隔离 + platform_admin override
-- ==========================================
DROP POLICY IF EXISTS agent_sessions_schema_isolation ON gamify_confetti;
CREATE POLICY agent_sessions_schema_isolation ON gamify_confetti
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_platform_admin ON gamify_confetti;
CREATE POLICY agent_sessions_platform_admin ON gamify_confetti
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;
-- 2026-09-10-p3d6-schema-template.sql
-- v0.99 P0-4 Stage 4.3 模板 (P2 阶段 fill)
-- 表: gamify_votes (per G5 vote (SRS-CANVAS-GAMIFY-001))
-- v0.99 P0-4 Stage 4.3 = P3-D.6 14+15 张表真实 schema 模板
-- (per v0.94 §3 已知缺口 (a) 'P0-4 阶段 26 张占位表, P2 阶段 worker 子代理 + P3-D.6 阶段 2 任务 2.x 实跑时 ALTER TABLE CREATE TABLE 真实 schema 替换占位' 跨 session 续做)
--
-- 本模板 1 张占位表 `gamify_votes` 完整 schema (含 CREATE TABLE IF NOT EXISTS + 7 类 RLS policy + IF NOT EXISTS idempotent + DROP IF EXISTS 兼容 PG 9.5+),
-- P2 阶段 worker 子代理 复制模板改 table name + column name 走 14 张表.
--
-- 守门 #13 a 100% RLS: ENABLE + FORCE + 7 类 policy
-- 守门 #13 b 物理删除禁止: 4 类 CRUD delete 仅 platform_admin
-- 守门 #13 c M SCD Type 2: pgpool_version 字段
-- 守门 #13 d T 100% audit: audit trigger 跨 RLS (per ADR-0043 WORM)
-- 守门 #1 禁回溯叙事: 不重写 v0.82 tenant_pools DDL, 仅新 commit + 模板声明
-- 守门 #11 缺标比错标: P0-4 阶段 1 张占位表完整 schema, P2 阶段 worker 子代理 fill 13 张

BEGIN;

-- ==========================================
-- 1. gamify_votes 表 (per DD-CANVAS-AGENT-001 §4.14.1 + 守门 #13 c SCD Type 2)
-- 模板: P2 阶段 worker 子代理 改 table name + column name 走 14 张
-- ==========================================
CREATE TABLE IF NOT EXISTS gamify_votes (
    -- 业务字段 (per DD §4.14.1)
    id              UUID NOT NULL,
    tenant_id       UUID NOT NULL,                        -- 守门 #13 a 100% RLS 13 类必带
    agent_id        UUID NOT NULL,                        -- 关联 agent 域 (per DD-CANVAS-AGENT-001)
    session_token   TEXT NOT NULL,                        -- 会话 token (per OAuth2 server v0.43 模式)
    status          TEXT NOT NULL DEFAULT 'Active',       -- Active/Expired/Revoked (per §5 状态机)
    expires_at      TIMESTAMPTZ NOT NULL,                 -- 过期时间 (per OAuth2 短期 token)
    schema_name     TEXT NOT NULL DEFAULT 'public',       -- 守门 #13 a + §13.5 多 schema
    -- 审计字段 (守门 #13 d T 100% audit + ADR-0043 WORM append-only)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID NOT NULL,
    pgpool_version  BIGINT NOT NULL DEFAULT 1,            -- 守门 #13 c SCD Type 2
    -- 显式主键
    PRIMARY KEY (id, pgpool_version),
    UNIQUE (tenant_id, pgpool_version)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_agent_sessions_tenant_id
    ON gamify_votes (tenant_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_agent_id
    ON gamify_votes (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_expires_at
    ON gamify_votes (expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_status
    ON gamify_votes (status)
    WHERE status != 'Active';

-- 当前 SCD Type 2 "有效" version 视图
CREATE OR REPLACE VIEW v_agent_sessions_current AS
SELECT DISTINCT ON (tenant_id, agent_id) *
FROM gamify_votes
ORDER BY tenant_id, agent_id, pgpool_version DESC;

-- AuditEvent WORM 触发器 (守门 #13 d 100% audit + ADR-0043 WORM)
CREATE OR REPLACE FUNCTION agent_sessions_audit_trigger() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO audit_audit_event (
        id, tenant_id, source_kind, source_id, action, row_data, actor_id, created_at
    ) VALUES (
        gen_random_uuid(),
        COALESCE(NEW.tenant_id, OLD.tenant_id),
        'AgentSession',
        COALESCE(NEW.id, OLD.id),
        TG_OP,
        to_jsonb(COALESCE(NEW, OLD)),
        COALESCE(NEW.updated_by, OLD.updated_by, NEW.created_by, OLD.created_by),
        NOW()
    );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_agent_sessions_audit
    AFTER INSERT OR UPDATE OR DELETE ON gamify_votes
    FOR EACH ROW
    EXECUTE FUNCTION agent_sessions_audit_trigger();

-- ==========================================
-- 2. RLS 7 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 模板: 复制到 14 张表 + 改 table name
-- ==========================================
ALTER TABLE gamify_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamify_votes FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS agent_sessions_select ON gamify_votes;
CREATE POLICY agent_sessions_select ON gamify_votes
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_insert ON gamify_votes;
CREATE POLICY agent_sessions_insert ON gamify_votes
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_update ON gamify_votes;
CREATE POLICY agent_sessions_update ON gamify_votes
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_delete ON gamify_votes;
CREATE POLICY agent_sessions_delete ON gamify_votes
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ==========================================
-- 3. RLS policy 占位: 跨 schema_name 隔离 + platform_admin override
-- ==========================================
DROP POLICY IF EXISTS agent_sessions_schema_isolation ON gamify_votes;
CREATE POLICY agent_sessions_schema_isolation ON gamify_votes
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_platform_admin ON gamify_votes;
CREATE POLICY agent_sessions_platform_admin ON gamify_votes
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;
-- 2026-09-10-p3d6-schema-template.sql
-- v0.99 P0-4 Stage 4.3 模板 (P2 阶段 fill)
-- 表: gamify_streaks (per G6 streak (SRS-CANVAS-GAMIFY-001))
-- v0.99 P0-4 Stage 4.3 = P3-D.6 14+15 张表真实 schema 模板
-- (per v0.94 §3 已知缺口 (a) 'P0-4 阶段 26 张占位表, P2 阶段 worker 子代理 + P3-D.6 阶段 2 任务 2.x 实跑时 ALTER TABLE CREATE TABLE 真实 schema 替换占位' 跨 session 续做)
--
-- 本模板 1 张占位表 `gamify_streaks` 完整 schema (含 CREATE TABLE IF NOT EXISTS + 7 类 RLS policy + IF NOT EXISTS idempotent + DROP IF EXISTS 兼容 PG 9.5+),
-- P2 阶段 worker 子代理 复制模板改 table name + column name 走 14 张表.
--
-- 守门 #13 a 100% RLS: ENABLE + FORCE + 7 类 policy
-- 守门 #13 b 物理删除禁止: 4 类 CRUD delete 仅 platform_admin
-- 守门 #13 c M SCD Type 2: pgpool_version 字段
-- 守门 #13 d T 100% audit: audit trigger 跨 RLS (per ADR-0043 WORM)
-- 守门 #1 禁回溯叙事: 不重写 v0.82 tenant_pools DDL, 仅新 commit + 模板声明
-- 守门 #11 缺标比错标: P0-4 阶段 1 张占位表完整 schema, P2 阶段 worker 子代理 fill 13 张

BEGIN;

-- ==========================================
-- 1. gamify_streaks 表 (per DD-CANVAS-AGENT-001 §4.14.1 + 守门 #13 c SCD Type 2)
-- 模板: P2 阶段 worker 子代理 改 table name + column name 走 14 张
-- ==========================================
CREATE TABLE IF NOT EXISTS gamify_streaks (
    -- 业务字段 (per DD §4.14.1)
    id              UUID NOT NULL,
    tenant_id       UUID NOT NULL,                        -- 守门 #13 a 100% RLS 13 类必带
    agent_id        UUID NOT NULL,                        -- 关联 agent 域 (per DD-CANVAS-AGENT-001)
    session_token   TEXT NOT NULL,                        -- 会话 token (per OAuth2 server v0.43 模式)
    status          TEXT NOT NULL DEFAULT 'Active',       -- Active/Expired/Revoked (per §5 状态机)
    expires_at      TIMESTAMPTZ NOT NULL,                 -- 过期时间 (per OAuth2 短期 token)
    schema_name     TEXT NOT NULL DEFAULT 'public',       -- 守门 #13 a + §13.5 多 schema
    -- 审计字段 (守门 #13 d T 100% audit + ADR-0043 WORM append-only)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      UUID NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      UUID NOT NULL,
    pgpool_version  BIGINT NOT NULL DEFAULT 1,            -- 守门 #13 c SCD Type 2
    -- 显式主键
    PRIMARY KEY (id, pgpool_version),
    UNIQUE (tenant_id, pgpool_version)
);

-- 索引 (per §6.1 query 优化)
CREATE INDEX IF NOT EXISTS idx_agent_sessions_tenant_id
    ON gamify_streaks (tenant_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_agent_id
    ON gamify_streaks (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_expires_at
    ON gamify_streaks (expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_status
    ON gamify_streaks (status)
    WHERE status != 'Active';

-- 当前 SCD Type 2 "有效" version 视图
CREATE OR REPLACE VIEW v_agent_sessions_current AS
SELECT DISTINCT ON (tenant_id, agent_id) *
FROM gamify_streaks
ORDER BY tenant_id, agent_id, pgpool_version DESC;

-- AuditEvent WORM 触发器 (守门 #13 d 100% audit + ADR-0043 WORM)
CREATE OR REPLACE FUNCTION agent_sessions_audit_trigger() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO audit_audit_event (
        id, tenant_id, source_kind, source_id, action, row_data, actor_id, created_at
    ) VALUES (
        gen_random_uuid(),
        COALESCE(NEW.tenant_id, OLD.tenant_id),
        'AgentSession',
        COALESCE(NEW.id, OLD.id),
        TG_OP,
        to_jsonb(COALESCE(NEW, OLD)),
        COALESCE(NEW.updated_by, OLD.updated_by, NEW.created_by, OLD.created_by),
        NOW()
    );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_agent_sessions_audit
    AFTER INSERT OR UPDATE OR DELETE ON gamify_streaks
    FOR EACH ROW
    EXECUTE FUNCTION agent_sessions_audit_trigger();

-- ==========================================
-- 2. RLS 7 类 policy (per v0.92 + v0.97 DROP IF EXISTS 兼容 PG 9.5+)
-- 模板: 复制到 14 张表 + 改 table name
-- ==========================================
ALTER TABLE gamify_streaks ENABLE ROW LEVEL SECURITY;
ALTER TABLE gamify_streaks FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS agent_sessions_select ON gamify_streaks;
CREATE POLICY agent_sessions_select ON gamify_streaks
    FOR SELECT
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_insert ON gamify_streaks;
CREATE POLICY agent_sessions_insert ON gamify_streaks
    FOR INSERT
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_update ON gamify_streaks;
CREATE POLICY agent_sessions_update ON gamify_streaks
    FOR UPDATE
    USING (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    )
    WITH CHECK (
        tenant_id::text = current_setting('app.current_tenant_id', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_delete ON gamify_streaks;
CREATE POLICY agent_sessions_delete ON gamify_streaks
    FOR DELETE
    USING (
        current_setting('app.is_admin', true) = 'true'
    );

-- ==========================================
-- 3. RLS policy 占位: 跨 schema_name 隔离 + platform_admin override
-- ==========================================
DROP POLICY IF EXISTS agent_sessions_schema_isolation ON gamify_streaks;
CREATE POLICY agent_sessions_schema_isolation ON gamify_streaks
    FOR ALL
    USING (
        schema_name = current_setting('app.current_schema_name', true)
        OR current_setting('app.is_admin', true) = 'true'
    );

DROP POLICY IF EXISTS agent_sessions_platform_admin ON gamify_streaks;
CREATE POLICY agent_sessions_platform_admin ON gamify_streaks
    FOR ALL
    TO platform_admin
    USING (true)
    WITH CHECK (true);

COMMIT;

COMMIT;
