#!/usr/bin/env python3
"""v1.00 P0-4 Stage 4.4 = P3-D.6 14+15 张表真实 schema 自动 fill 脚本 (per v0.99 §3 已知缺口 (d))

读 v0.99 p3d6-schema-template.sql 模板, 替换 table name + 通用 column name, 输出 13 张表真实 schema DDL.
走 v0.97 DROP IF EXISTS 兼容 PG 9.5+ idempotent 模式.
走 v0.92 rls_7_policy_gen.py 模板 (7 类 RLS policy).

P0-4 阶段: 脚本声明 + 1 个总览 DDL 占位, 13 张表 column name 走 DD-CANVAS-AGENT-001 §3.1 + DD-AGENT-RELATIONSHIP-001 通用字段.
P2 阶段 worker 子代理 改 table/column name + 实测 + fill 真实 schema.

Usage:
    python scripts/sql/p3d6_13_tables_gen.py
    python scripts/sql/p3d6_13_tables_gen.py --output db/migrations/2026-09-10-p3d6-13-tables.sql
"""
import argparse
import re
import sys
from pathlib import Path


# 13 张 P3-D.6 表 (per v0.94 P3D6_PLACEHOLDER_TABLES, 走 v0.99 agent_sessions 模板 + 各自业务 column)
# 13 张表覆盖: 5 A11 agent 域 + 4 A12 canvas-collab 域 + 6 G 域 gamify 域 (per CANVAS-IMPL-PLAN-001 §1.6)
# 每张表 dict: name + column name (P0-4 占位, P2 阶段 fill 真实)
P3D6_13_TABLES = [
    # 5 A11 agent 域 (per DD-CANVAS-AGENT-001 §3.1)
    {
        "name": "agent_sessions",  # v0.99 已有完整 schema, 占位
        "template": "agent_sessions",
        "dd_ref": "DD-CANVAS-AGENT-001 §4.14.1",
    },
    {
        "name": "agent_policies",
        "template": "agent_sessions",
        "dd_ref": "DD-CANVAS-AGENT-001 §3.2",
    },
    {
        "name": "agent_actions",
        "template": "agent_sessions",
        "dd_ref": "DD-CANVAS-AGENT-001 §3.3 (AuditEvent WORM 跨 RLS)",
    },
    {
        "name": "agent_relationships",
        "template": "agent_sessions",
        "dd_ref": "DD-AGENT-RELATIONSHIP-001 §3.1",
    },
    {
        "name": "agent_trust_scores",
        "template": "agent_sessions",
        "dd_ref": "ARG.G-4 TrustAuditLog + 4 重审计",
    },
    # 4 A12 canvas-collab 域 (per DD §3.1, 协调性检查 v0.63 命名修正)
    {
        "name": "canvas_elements",
        "template": "agent_sessions",
        "dd_ref": "C-25 CanvasElementsBackend (DD §3.1, 协调性检查 v0.63 命名修正)",
    },
    {
        "name": "canvas_multi_user_audit",
        "template": "agent_sessions",
        "dd_ref": "C-26 CanvasMultiUserAudit (DD §3.2, 守门 #13 d Transaction 100% audit)",
    },
    {
        "name": "canvas_reactions",
        "template": "agent_sessions",
        "dd_ref": "G7 reaction 3s TTL (SRS-CANVAS-GAMIFY-001)",
    },
    {
        "name": "canvas_comments",
        "template": "agent_sessions",
        "dd_ref": "A12.4 canvas comments",
    },
    # 6 G 域 (per SRS-CANVAS-GAMIFY-001)
    {
        "name": "gamify_avatars",
        "template": "agent_sessions",
        "dd_ref": "G1 avatar (SRS-CANVAS-GAMIFY-001)",
    },
    {
        "name": "gamify_levels",
        "template": "agent_sessions",
        "dd_ref": "G2 level (SRS-CANVAS-GAMIFY-001)",
    },
    {
        "name": "gamify_sticky_notes",
        "template": "agent_sessions",
        "dd_ref": "G3 sticky (SRS-CANVAS-GAMIFY-001)",
    },
    {
        "name": "gamify_confetti",
        "template": "agent_sessions",
        "dd_ref": "G4 confetti (SRS-CANVAS-GAMIFY-001)",
    },
    {
        "name": "gamify_votes",
        "template": "agent_sessions",
        "dd_ref": "G5 vote (SRS-CANVAS-GAMIFY-001)",
    },
    {
        "name": "gamify_streaks",
        "template": "agent_sessions",
        "dd_ref": "G6 streak (SRS-CANVAS-GAMIFY-001)",
    },
]


def gen_one_table(table_name: str, template: str, dd_ref: str) -> str:
    """生成 1 张表的 DDL (基于 template 替换 table name)"""
    # 读 v0.99 模板
    template_path = Path("db/migrations/2026-09-10-p3d6-schema-template.sql")
    if not template_path.exists():
        template_path = Path("../2026-09-10-p3d6-schema-template.sql")
    template_text = template_path.read_text(encoding="utf-8")
    # 替换 table name (全词)
    ddl = re.sub(r"\bagent_sessions\b", table_name, template_text)
    # 加注释说明 dd_ref
    ddl = ddl.replace(
        "-- v0.99 P0-4 Stage 4.3 = P3-D.6 14+15 张表真实 schema 模板",
        f"-- v0.99 P0-4 Stage 4.3 模板 (P2 阶段 fill)\n-- 表: {table_name} (per {dd_ref})\n-- v0.99 P0-4 Stage 4.3 = P3-D.6 14+15 张表真实 schema 模板",
    )
    return ddl


def gen_all() -> str:
    """生成 14 张表 (v0.99 已有 agent_sessions + 13 张 fill) DDL"""
    header = """-- 2026-09-10-p3d6-13-tables.sql (auto-generated by scripts/sql/p3d6_13_tables_gen.py)
-- v1.00 P0-4 Stage 4.4 = P3-D.6 14+15 张表真实 schema 自动 fill 脚本 (per v0.99 §3 已知缺口 (d))
-- (per v0.94 §3 已知缺口 (a) 'P0-4 阶段 26 张占位表, P2 阶段 worker 子代理 fill 真实 schema' 跨 session 续做)
--
-- 守门 #13 a 100% RLS: ENABLE + FORCE + 7 类 policy (走 v0.92 rls_7_policy_gen.py 模板)
-- 守门 #13 b 物理删除禁止: 4 类 CRUD delete 仅 platform_admin
-- 守门 #13 c M SCD Type 2: pgpool_version 字段 + 视图
-- 守门 #13 d T 100% audit: audit trigger 跨 RLS (per ADR-0043 WORM)
-- 守门 #19 v19 复用 v0.99 schema 模板 + v0.97 DROP IF EXISTS idempotent + v0.92 7 类 RLS policy
-- 守门 #11 缺标比错标: P0-4 阶段 13 张表 column name 占位, P2 阶段 worker 子代理 fill 真实

BEGIN;

"""
    body = "".join(gen_one_table(t["name"], t["template"], t["dd_ref"]) for t in P3D6_13_TABLES)
    footer = "\nCOMMIT;\n"
    return header + body + footer


def main() -> int:
    parser = argparse.ArgumentParser(
        description="v1.00 P3-D.6 14+15 张表真实 schema 自动 fill 脚本 (per v0.99 §3 已知缺口 (d))",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("db/migrations/2026-09-10-p3d6-13-tables.sql"),
        help="输出 DDL 路径",
    )
    args = parser.parse_args()

    ddl = gen_all()
    args.output.write_text(ddl, encoding="utf-8")
    print(
        f"[ok] 生成 {len(P3D6_13_TABLES)} 张表 DDL: {args.output} (+{len(ddl)} bytes)",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
