#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
scripts/automation/memgraph_setup.py — Memgraph local stack bootstrap
(per docs/briefs/arg-01-arg-crate-skeleton.md §2.1 C + WBS §14.11 ARG.1)

Per 守门 #1 v19 (P 子项 Python 化) + 守门 #1 v15 (新事件 docs 同步允许) +
守门 #5 (env 安全, 2026-08-27 11:06 JST hard ban):

- 启动 Memgraph via `docker compose up` (Bolt 7687 + HTTP 7444)
- 等待 health check 通过 (per Memgraph mgmt API `/api/v1/health`)
- 写 .env stub (不打印明文) — 守门 #5
- 失败兜底: 详细错误信息 + 退出码

约束:
- 标准库 only (per 守门 #1 v1)
- 不调外部 RPC, 走 subprocess (per 守门 #9 v3)
- env 连接串走 $env:MEMGRAPH_BOLT_URL, 不打印 (per 守门 #5)

用法:
    python scripts/automation/memgraph_setup.py
    python scripts/automation/memgraph_setup.py --skip-docker   # 假设已运行
    python scripts/automation/memgraph_setup.py --env-file .env.memgraph
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import time
from pathlib import Path

ROOT_DEFAULT = Path(__file__).resolve().parent.parent.parent
ENV_FILE_DEFAULT = ROOT_DEFAULT / ".env.memgraph"

# Memgraph 默认端口 + mgmt API path (per Memgraph 2.x documentation).
DEFAULT_BOLT_URL = "bolt://localhost:7687"
DEFAULT_HTTP_URL = "http://localhost:7444"
DEFAULT_USER = "memgraph"
DEFAULT_PASSWORD = "memgraph"
HEALTH_PATH = "/api/v1/health"

# 启动容器用 docker compose snippet. 落临时 compose file 而不是依赖 host
# 已有 docker-compose.yml, 避免污染 repo.
COMPOSE_SNIPPET = """\
services:
  memgraph:
    image: memgraph/memgraph:2.14
    container_name: arg-memgraph
    ports:
      - "7687:7687"   # Bolt
      - "7444:7444"   # HTTP / mgmt
    environment:
      - MEMGRAPH_USER={user}
      - MEMGRAPH_PASSWORD={password}
    volumes:
      - memgraph_data:/var/lib/memgraph
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7444{health_path}"]
      interval: 5s
      timeout: 3s
      retries: 12

volumes:
  memgraph_data:
""".format(user=DEFAULT_USER, password=DEFAULT_PASSWORD, health_path=HEALTH_PATH)


def write_compose_file(target: Path) -> Path:
    """写 docker-compose.memgraph.yml, 跑完让调用方保留文件方便重跑."""
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(COMPOSE_SNIPPET, encoding="utf-8")
    return target


def docker_up(compose_file: Path) -> int:
    """跑 docker compose up -d.  返回 exit code."""
    proc = subprocess.run(
        ["docker", "compose", "-f", str(compose_file), "up", "-d"],
        capture_output=True,
        text=True,
        timeout=120,
    )
    return proc.returncode


def docker_ps(compose_file: Path) -> tuple:
    """跑 docker compose ps.  返回 (exit_code, stdout, stderr)."""
    proc = subprocess.run(
        ["docker", "compose", "-f", str(compose_file), "ps"],
        capture_output=True,
        text=True,
        timeout=15,
    )
    return proc.returncode, proc.stdout, proc.stderr


def health_probe(http_url: str, retries: int = 12, interval_sec: float = 5.0) -> bool:
    """探测 Memgraph mgmt API health.  返回 True / False.

    不打印 http_url 中可能含的连接串, 守门 #5 (本次默认 localhost, 仍按规).
    """
    import urllib.request
    import urllib.error

    url = f"{http_url}{HEALTH_PATH}"
    for attempt in range(1, retries + 1):
        try:
            with urllib.request.urlopen(url, timeout=3) as resp:  # noqa: S310
                if 200 <= resp.status < 300:
                    return True
        except (urllib.error.URLError, ConnectionError, TimeoutError):
            pass
        time.sleep(interval_sec)
    return False


def write_env_stub(target: Path, bolt_url: str, user: str, password: str) -> None:
    """写 .env stub 文件, 不打印明文密码.

    守门 #5: 密码写到 .env 文件但绝不打印到 stdout/stderr.
    """
    lines = [
        "# Generated by scripts/automation/memgraph_setup.py",
        "# DO NOT COMMIT (gitignore .env.memgraph)",
        f"MEMGRAPH_BOLT_URL={bolt_url}",
        f"MEMGRAPH_HTTP_URL={DEFAULT_HTTP_URL}",
        f"MEMGRAPH_USER={user}",
        "MEMGRAPH_PASSWORD=" + password,  # literal, NOT printed
        "",
    ]
    target.write_text("\n".join(lines), encoding="utf-8")
    # .gitignore 追加 (idempotent).
    gitignore = target.parent / ".gitignore"
    extra = target.name
    if gitignore.exists():
        existing = gitignore.read_text(encoding="utf-8")
        if extra not in existing:
            gitignore.write_text(existing.rstrip() + "\n" + extra + "\n", encoding="utf-8")
    else:
        gitignore.write_text(extra + "\n", encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="Memgraph local stack bootstrap (ARG.1)")
    parser.add_argument("--skip-docker", action="store_true",
                        help="Skip docker compose up, assume Memgraph already running")
    parser.add_argument("--compose-file", type=Path,
                        default=ROOT_DEFAULT / "docker-compose.memgraph.yml",
                        help="docker compose file path")
    parser.add_argument("--env-file", type=Path, default=ENV_FILE_DEFAULT,
                        help=".env stub output path (gitignored)")
    parser.add_argument("--bolt-url", default=os.environ.get("MEMGRAPH_BOLT_URL", DEFAULT_BOLT_URL),
                        help="Bolt URL (default from env or localhost)")
    parser.add_argument("--http-url", default=os.environ.get("MEMGRAPH_HTTP_URL", DEFAULT_HTTP_URL),
                        help="HTTP mgmt URL (default from env or localhost)")
    parser.add_argument("--user", default=os.environ.get("MEMGRAPH_USER", DEFAULT_USER),
                        help="Memgraph user")
    parser.add_argument("--password",
                        default=os.environ.get("MEMGRAPH_PASSWORD", DEFAULT_PASSWORD),
                        help="Memgraph password (per 守门 #5: never printed)")
    args = parser.parse_args()

    compose_file = args.compose_file
    env_file = args.env_file

    if not args.skip_docker:
        write_compose_file(compose_file)
        rc = docker_up(compose_file)
        if rc != 0:
            print(f"ERROR: docker compose up failed (rc={rc})", file=sys.stderr)
            sys.exit(rc)

    # health probe
    if not health_probe(args.http_url):
        print(f"ERROR: Memgraph health probe failed at {args.http_url}{HEALTH_PATH}", file=sys.stderr)
        sys.exit(2)

    # 写 .env stub (密码不打印)
    write_env_stub(env_file, args.bolt_url, args.user, args.password)
    print(f"OK: Memgraph healthy at {args.http_url}")
    print(f"OK: env stub written to {env_file} (password NOT echoed per 守门 #5)")


if __name__ == "__main__":
    main()
