#!/usr/bin/env python3
"""Patch star-dispatcher/src/lib.rs: add H.1 LangGraph 2-level hierarchical integration tests"""
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

root = Path(r"D:\Star\.worktrees\feat-auto-20260904-1c260bc7")
fp = root / "crates/star-dispatcher/src/lib.rs"
text = fp.read_text(encoding="utf-8")

final_end = text.rfind("}\n")

h1_tests = (
    "\n"
    "    /// H.1 PoC test 1: SubAgentPool 注册 + spawn 限额\n"
    "    #[tokio::test]\n"
    "    async fn subagentpool_spawn_with_limit() {\n"
    "        let pool = SubAgentPool::with_max_parallel(2);\n"
    "        pool.register(Arc::new(StubSubAgent::new(SubAgentArchetype::CodeReview))).await;\n"
    "        pool.register(Arc::new(StubSubAgent::new(SubAgentArchetype::TestGen))).await;\n"
    "        // 2 个 spawn 通过\n"
    "        for i in 0..2 {\n"
    "            let task = AgentTask {\n"
    "                task_id: Uuid::new_v4(),\n"
    "                tenant_id: Uuid::new_v4(),\n"
    "                kind: \"test\".into(),\n"
    "                payload: serde_json::json!({\"i\": i}),\n"
    "                idempotency_key: format!(\"k{}\", i),\n"
    "                created_at_ms: now_ms(),\n"
    "                state: TaskState::Pending,\n"
    "                state_history: vec![],\n"
    "            };\n"
    "            let archetype = if i == 0 {\n"
    "                SubAgentArchetype::CodeReview\n"
    "            } else {\n"
    "                SubAgentArchetype::TestGen\n"
    "            };\n"
    "            pool.spawn(archetype, &task).await.unwrap();\n"
    "        }\n"
    "        assert_eq!(pool.active_count().await, 2);\n"
    "        // 第 3 个 spawn 触发 PoolExhausted\n"
    "        let task3 = AgentTask {\n"
    "            task_id: Uuid::new_v4(),\n"
    "            tenant_id: Uuid::new_v4(),\n"
    "            kind: \"test\".into(),\n"
    "            payload: serde_json::json!({}),\n"
    "            idempotency_key: \"k3\".into(),\n"
    "            created_at_ms: now_ms(),\n"
    "            state: TaskState::Pending,\n"
    "            state_history: vec![],\n"
    "        };\n"
    "        let res = pool.spawn(SubAgentArchetype::CodeReview, &task3).await;\n"
    "        assert!(matches!(res, Err(DispatchError::PoolExhausted { .. })));\n"
    "    }\n"
    "\n"
    "    /// H.1 PoC test 2: SubAgentPool spawn 未知 archetype -> PoolNotFound\n"
    "    #[tokio::test]\n"
    "    async fn subagentpool_spawn_unregistered_archetype() {\n"
    "        let pool = SubAgentPool::new();\n"
    "        // 没注册任何 SA\n"
    "        let task = AgentTask {\n"
    "            task_id: Uuid::new_v4(),\n"
    "            tenant_id: Uuid::new_v4(),\n"
    "            kind: \"x\".into(),\n"
    "            payload: serde_json::json!({}),\n"
    "            idempotency_key: \"k\".into(),\n"
    "            created_at_ms: now_ms(),\n"
    "            state: TaskState::Pending,\n"
    "            state_history: vec![],\n"
    "        };\n"
    "        let res = pool.spawn(SubAgentArchetype::DomainDev, &task).await;\n"
    "        assert!(matches!(res, Err(DispatchError::PoolNotFound(_))));\n"
    "    }\n"
    "\n"
    "    /// H.1 PoC test 3: TopAgent (L0) + SubAgentPool (L1) 2-level 集成 + Checkpoint 持久化\n"
    "    #[tokio::test]\n"
    "    async fn topagent_l0_l1_2level_with_checkpoint() {\n"
    "        let top = TopAgent::new();\n"
    "        // L0 Top Agent 派生 L1 CodeReview + L1 TestGen\n"
    "        top.pool()\n"
    "            .register(Arc::new(StubSubAgent::new(SubAgentArchetype::CodeReview)))\n"
    "            .await;\n"
    "        top.pool()\n"
    "            .register(Arc::new(StubSubAgent::new(SubAgentArchetype::TestGen)))\n"
    "            .await;\n"
    "        // 派生 2 sub-agent task + 自动 checkpoint\n"
    "        let mut task_ids = vec![];\n"
    "        for archetype in [SubAgentArchetype::CodeReview, SubAgentArchetype::TestGen] {\n"
    "            let task_id = Uuid::new_v4();\n"
    "            let task = AgentTask {\n"
    "                task_id,\n"
    "                tenant_id: Uuid::new_v4(),\n"
    "                kind: archetype.name().into(),\n"
    "                payload: serde_json::json!({\"i\": task_ids.len()}),\n"
    "                idempotency_key: format!(\"top_k{}\", task_ids.len()),\n"
    "                created_at_ms: now_ms(),\n"
    "                state: TaskState::Pending,\n"
    "                state_history: vec![],\n"
    "            };\n"
    "            top.dispatch_with_checkpoint(archetype, &task).await.unwrap();\n"
    "            task_ids.push(task_id);\n"
    "        }\n"
    "        // 2 个 active sub-agent\n"
    "        assert_eq!(top.pool().active_count().await, 2);\n"
    "        // 2 个 checkpoint 持久化\n"
    "        assert_eq!(top.checkpoints().count().await, 2);\n"
    "        // 每个 task 能从 checkpoint 恢复\n"
    "        for task_id in &task_ids {\n"
    "            let cp = top.checkpoints().latest_for_task(*task_id).await.unwrap();\n"
    "            assert_eq!(cp.task_id, *task_id);\n"
    "        }\n"
    "    }\n"
)

new_text = text[:final_end] + h1_tests + text[final_end:]
fp.write_text(new_text, encoding="utf-8")
print(f"OK: new size {len(new_text)}")
