import {
  Inbox,
  CheckSquare,
  FolderKanban,
  Bot,
  BarChart3,
  Settings,
  Trello,
  SquareChartGantt,
  LayoutDashboard,
  Users,
  Building2,
  FileText,
  MessageSquare,
  Workflow,
  ShieldCheck,
  Hammer,
  Calendar,
  GitBranch,
  MessageCircleWarning,
  ListTodo,
  GitFork,
  Plug,
  Search,
  Server,
  Boxes,
  History,
  Zap,
  Network,
  Briefcase,
  Key,
  Terminal,
  Sparkles,
  Monitor,
  FolderOpen,
  Smartphone,
  RefreshCw,
} from "lucide-react";

export type ModuleCategory =
  | "core"
  | "work"
  | "agent"
  | "integration"
  | "system";

export interface ModuleDefinition {
  id: string;
  label: string;
  code: string;
  href: string;
  category: ModuleCategory;
  categoryLabel: string;
  description: string;
  icon: React.ElementType;
  isCore?: boolean;
  count?: number;
}

export const ALL_MODULES: ModuleDefinition[] = [
  // ── Core Workspaces ──────────────────────────────────────────────
  {
    id: "inbox",
    label: "Inbox",
    code: "01",
    href: "/inbox",
    category: "core",
    categoryLabel: "Core Workspace",
    description: "通知中心、@提及与审计流聚合工作台",
    icon: Inbox,
    isCore: true,
    count: 3,
  },
  {
    id: "issues",
    label: "Issues",
    code: "02",
    href: "/issues",
    category: "core",
    categoryLabel: "Core Workspace",
    description: "工作项与任务看板 / 树形全景视图",
    icon: CheckSquare,
    isCore: true,
  },
  {
    id: "projects",
    label: "Projects",
    code: "03",
    href: "/projects",
    category: "core",
    categoryLabel: "Core Workspace",
    description: "多面板项目工作区 (Kanban / Timeline / Backlog / Agents / Worktrees)",
    icon: FolderKanban,
    isCore: true,
  },
  {
    id: "agents",
    label: "Agents",
    code: "04",
    href: "/agents",
    category: "core",
    categoryLabel: "Core Workspace",
    description: "智能 Agent 运行状态、编排、会话与执行日志",
    icon: Bot,
    isCore: true,
  },
  {
    id: "analytics",
    label: "Analytics",
    code: "05",
    href: "/analytics",
    category: "core",
    categoryLabel: "Core Workspace",
    description: "工程效能大盘、燃尽图与遥测指标统计",
    icon: BarChart3,
    isCore: true,
  },
  {
    id: "settings",
    label: "Settings",
    code: "06",
    href: "/settings",
    category: "core",
    categoryLabel: "Core Workspace",
    description: "租户全局配置、团队成员、安全与权限管理",
    icon: Settings,
    isCore: true,
  },
  {
    id: "remote",
    label: "Remote Control",
    code: "M",
    href: "/remote",
    category: "core",
    categoryLabel: "Core Workspace",
    description: "手机端远程连接 desktop / terminal / files (per 2026-09-01 PHASE-MOBILE-PWA v0.2)",
    icon: Smartphone,
    isCore: true,
  },

  // ── Tactical Views ───────────────────────────────────────────────
  {
    id: "kanban",
    label: "Kanban Board",
    code: "KB",
    href: "/projects?tab=kanban",
    category: "work",
    categoryLabel: "Work Management",
    description: "4 态泳道即时拖拽任务看板",
    icon: Trello,
  },
  {
    id: "timeline",
    label: "Timeline & Gantt",
    code: "TL",
    href: "/projects?tab=timeline",
    category: "work",
    categoryLabel: "Work Management",
    description: "甘特图排期、里程碑与日历时间线联动",
    icon: SquareChartGantt,
  },
  {
    id: "backlog",
    label: "Backlog",
    code: "BL",
    href: "/projects?tab=backlog",
    category: "work",
    categoryLabel: "Work Management",
    description: "需求待办列表与优先级排期池",
    icon: LayoutDashboard,
  },

  // ── Agent & Worktree Tools ───────────────────────────────────────
  {
    id: "agent-windows",
    label: "Agent Windows",
    code: "WIN",
    href: "/agent-windows",
    category: "agent",
    categoryLabel: "Worktree / Agent",
    description: "Agent 多终端并行任务执行窗口",
    icon: Sparkles,
  },
  {
    id: "worktree",
    label: "Worktree Manager",
    code: "WT",
    href: "/worktree",
    category: "agent",
    categoryLabel: "Worktree / Agent",
    description: "Git Worktree 隔离分支工作流与状态机",
    icon: GitBranch,
  },
  {
    id: "validation",
    label: "Validation Test",
    code: "VAL",
    href: "/validation",
    category: "agent",
    categoryLabel: "Worktree / Agent",
    description: "自动化用例验证与断言测试套件",
    icon: ShieldCheck,
  },
  {
    id: "context",
    label: "Context Graph",
    code: "CTX",
    href: "/context",
    category: "agent",
    categoryLabel: "Worktree / Agent",
    description: "Agent 上下文知识图谱与决策包",
    icon: ListTodo,
  },
  {
    id: "feedback",
    label: "Agent Feedback",
    code: "FB",
    href: "/feedback",
    category: "agent",
    categoryLabel: "Worktree / Agent",
    description: "人机协作反馈回路与异常预警",
    icon: MessageCircleWarning,
  },

  // ── Work Management Modules ──────────────────────────────────────
  {
    id: "workflow",
    label: "Workflow Engine",
    code: "WF",
    href: "/workflow",
    category: "work",
    categoryLabel: "Work Management",
    description: "自动化工作流编排与状态流转规则",
    icon: Workflow,
  },
  {
    id: "development",
    label: "Development Hub",
    code: "DEV",
    href: "/development",
    category: "work",
    categoryLabel: "Work Management",
    description: "变更集 ChangeSet 与分支代码协同",
    icon: Hammer,
  },
  {
    id: "planning",
    label: "Planning Hub",
    code: "PLN",
    href: "/planning",
    category: "work",
    categoryLabel: "Work Management",
    description: "Sprint 迭代规划与容量负荷评估",
    icon: Calendar,
  },

  // ── Integrations & Security ──────────────────────────────────────
  {
    id: "scm",
    label: "SCM Provider",
    code: "SCM",
    href: "/scm",
    category: "integration",
    categoryLabel: "Integration & Security",
    description: "Git VCS 仓库与 Pull Request 追踪",
    icon: GitFork,
  },
  {
    id: "integration",
    label: "MCP Integrations",
    code: "MCP",
    href: "/integration",
    category: "integration",
    categoryLabel: "Integration & Security",
    description: "第三方工具链与 MCP 服务连接网关",
    icon: Plug,
  },
  {
    id: "api-keys",
    label: "API Keys & Secrets",
    code: "KEY",
    href: "/settings/api-keys",
    category: "integration",
    categoryLabel: "Integration & Security",
    description: "凭据密钥保管库与模型 API Key 配置",
    icon: Key,
  },
  {
    id: "cli-profiles",
    label: "CLI Profiles",
    code: "CLI",
    href: "/settings/cli-profiles",
    category: "integration",
    categoryLabel: "Integration & Security",
    description: "命令行环境配置与凭据模板",
    icon: Terminal,
  },
  {
    id: "search",
    label: "Universal Search",
    code: "SRC",
    href: "/search",
    category: "integration",
    categoryLabel: "Integration & Security",
    description: "全域跨模块语义检索与索引",
    icon: Search,
  },

  // ── System & Meta ────────────────────────────────────────────────
  {
    id: "local-runtime",
    label: "Local Runtime",
    code: "RUN",
    href: "/local-runtime",
    category: "system",
    categoryLabel: "System & Meta",
    description: "本地容器执行时与守护进程控制台",
    icon: Server,
  },
  {
    id: "audit",
    label: "Audit Log",
    code: "AUD",
    href: "/audit",
    category: "system",
    categoryLabel: "System & Meta",
    description: "不可篡改操作合规审计日志",
    icon: History,
  },
  {
    id: "automation",
    label: "Automation Triggers",
    code: "AUT",
    href: "/automation",
    category: "system",
    categoryLabel: "System & Meta",
    description: "事件驱动自动化与 Webhook 调度",
    icon: Zap,
  },
  {
    id: "relation",
    label: "Entity Relations",
    code: "REL",
    href: "/relation",
    category: "system",
    categoryLabel: "System & Meta",
    description: "跨域实体依赖网状图谱",
    icon: Network,
  },
  {
    id: "permission",
    label: "RBAC Permissions",
    code: "SEC",
    href: "/permission",
    category: "system",
    categoryLabel: "System & Meta",
    description: "细粒度角色权限策略矩阵",
    icon: ShieldCheck,
  },
  {
    id: "identity",
    label: "Identity & Members",
    code: "IDN",
    href: "/identity",
    category: "system",
    categoryLabel: "System & Meta",
    description: "成员账号、组织架构与鉴权身份",
    icon: Users,
  },
  {
    id: "tenant",
    label: "Tenant Admin",
    code: "TNT",
    href: "/tenant",
    category: "system",
    categoryLabel: "System & Meta",
    description: "多租户隔离与资源配额控制",
    icon: Building2,
  },
  // ── Refactor Sweep (per 2026-09-02 10:41 JST 拍板) ──
  // 分批对已完成任务做重构, 5 状态 todo/doing/testing/review/done 看板,
  // 走完一轮回到 todo, 累计轮次. 跟 Kanban 一样可自定义列.
  {
    id: "refactor",
    label: "Refactor Sweep",
    code: "RFS",
    href: "/refactor",
    category: "work",
    categoryLabel: "Work Management",
    description: "分批次重构已完成任务 · Jira 风格 todo→done 循环, 列可自定义",
    icon: RefreshCw,
  },
];

export const MODULE_MAP = new Map<string, ModuleDefinition>(
  ALL_MODULES.map((m) => [m.id, m])
);
