// SPDX-License-Identifier: MIT OR Apache-2.0
//! 5 内部协议 schema (per arch 2026-09-03-arg/06-arg-02-arg-bridge.md §2).
//!
//! Five protocols, one for each ARG effect dimension (per DD §5.2):
//!
//! 1. `arg_edge_changed`         — edge create / update / archive
//! 2. `arg_dispatch_route`       — dispatch override
//! 3. `arg_context_inject`       — context injection event
//! 4. `arg_trust_score_update`   — trust score delta
//! 5. `arg_achievement_unlocked` — achievement unlock
//!
//! All protocols are serialised as JSON and routed through a single
//! [`BridgeEnvelope`] over the in-process `tokio::sync::broadcast` channel
//! or the `sled`-backed [`crate::offline_queue::OfflineQueue`].

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Protocol #1: `arg_edge_changed` (4 维度 #1 主).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ArgEdgeChanged {
    /// Edge id (primary key in Memgraph).
    pub edge_id: Uuid,
    /// Source agent id.
    pub from_agent_id: Uuid,
    /// Target agent id.
    pub to_agent_id: Uuid,
    /// Relationship label, e.g. `"DELEGATES_TO"` (per DD §3.2.2).
    pub relationship_type: String,
    /// Weight in `[0.0, 1.0]`.
    pub weight: f64,
    /// Created-at timestamp.
    pub created_at: DateTime<Utc>,
    /// Originating sub-agent (`SA_01`..`SA_09` or `LEAD_*`).
    pub trigger_sa: String,
}

/// Protocol #2: `arg_dispatch_route` (4 维度 #1 dispatch 覆盖).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ArgDispatchRoute {
    /// Route id (Uuid v4).
    pub route_id: Uuid,
    /// Source agent id.
    pub from_agent_id: Uuid,
    /// Target agent id.
    pub to_agent_id: Uuid,
    /// Sub-agent type, e.g. `"SA_03"`.
    pub sa_type: String,
    /// Trust-weighted score in `[0.0, 1.0]`.
    pub weight: f64,
    /// Reason for the override (e.g. `"stand_in"` / `"delegate"`).
    pub override_reason: String,
    /// Created-at timestamp.
    pub created_at: DateTime<Utc>,
}

/// Protocol #3: `arg_context_inject` (4 维度 #2 上下文共享).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ArgContextInject {
    /// Inject id (Uuid v4).
    pub inject_id: Uuid,
    /// Source agent id.
    pub source_agent_id: Uuid,
    /// Target agent id.
    pub target_agent_id: Uuid,
    /// Free-form shared context payload.
    pub shared_context: serde_json::Value,
    /// Sub-agent type.
    pub sa_type: String,
    /// Created-at timestamp.
    pub created_at: DateTime<Utc>,
}

/// Protocol #4: `arg_trust_score_update` (4 维度 #3 信任度).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ArgTrustScoreUpdate {
    /// Agent whose score changed.
    pub agent_id: Uuid,
    /// Score before the change.
    pub old_score: f64,
    /// Score after the change.
    pub new_score: f64,
    /// Reason label, one of 5 (`success` / `failure` / `challenge_accept` /
    /// `challenge_reject` / `peer_review`).
    pub delta_reason: String,
    /// Originating sub-agent.
    pub trigger_sa: String,
    /// Created-at timestamp.
    pub created_at: DateTime<Utc>,
}

/// Protocol #5: `arg_achievement_unlocked` (8 拓扑成就).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ArgAchievementUnlocked {
    /// Unlock id (Uuid v4).
    pub unlock_id: Uuid,
    /// Agent that unlocked the achievement.
    pub agent_id: Uuid,
    /// Achievement id, e.g. `"TOP-001"`.
    pub achievement_id: String,
    /// Topology snapshot at the unlock instant.
    pub topology_snapshot: serde_json::Value,
    /// Unlock-text generated by `LLMService` (per ARG.1 llm 子模块).
    pub unlock_text: String,
    /// Created-at timestamp.
    pub created_at: DateTime<Utc>,
}

/// 5 协议 union — for `serde` tag dispatch.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum BridgeEnvelopeKind {
    /// Protocol #1.
    EdgeChanged(ArgEdgeChanged),
    /// Protocol #2.
    DispatchRoute(ArgDispatchRoute),
    /// Protocol #3.
    ContextInject(ArgContextInject),
    /// Protocol #4.
    TrustScoreUpdate(ArgTrustScoreUpdate),
    /// Protocol #5.
    AchievementUnlocked(ArgAchievementUnlocked),
}

impl BridgeEnvelopeKind {
    /// Stable string code used as a metric / log label.
    pub fn kind_str(&self) -> &'static str {
        match self {
            Self::EdgeChanged(_) => "arg_edge_changed",
            Self::DispatchRoute(_) => "arg_dispatch_route",
            Self::ContextInject(_) => "arg_context_inject",
            Self::TrustScoreUpdate(_) => "arg_trust_score_update",
            Self::AchievementUnlocked(_) => "arg_achievement_unlocked",
        }
    }
}

/// Single-envelope wrapper carrying an [`BridgeEnvelopeKind`] payload
/// together with the dispatch metadata used by the
/// [`crate::period_flush::PeriodFlushWorker`] and the
/// [`crate::offline_queue::OfflineQueue`].
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct BridgeEnvelope {
    /// Globally unique envelope id (per W/T/M idempotency).
    pub id: Uuid,
    /// Inner payload.
    pub kind: BridgeEnvelopeKind,
    /// Producer epoch counter (per producer, monotonic).
    pub epoch: u64,
    /// Enqueue timestamp.
    pub enqueued_at: DateTime<Utc>,
}

impl BridgeEnvelope {
    /// Build a new envelope around `kind` with the current wall clock and
    /// the given `id` + `epoch`.
    pub fn new(id: Uuid, kind: BridgeEnvelopeKind, epoch: u64) -> Self {
        Self {
            id,
            kind,
            epoch,
            enqueued_at: Utc::now(),
        }
    }

    /// Stable string code for the inner payload.
    pub fn kind_str(&self) -> &'static str {
        self.kind.kind_str()
    }
}
